@extends('layouts.app')
@section('title', __('hms::lang.rate_plans'))
@section('content')
@include('hms::layouts.nav')
<section class="content-header"><h1>@lang('hms::lang.rate_plans') <small>@lang('hms::lang.rate_plans_help')</small></h1></section>
<section class="content">
<div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">@lang('hms::lang.add_rate_plan')</h3></div><div class="box-body">
{!! Form::open(['route'=>'hms.rate_plans.store']) !!}<div class="row">
<div class="col-md-3"><div class="form-group">{!! Form::label('hms_property_id',__('hms::lang.property').':*') !!}{!! Form::select('hms_property_id',$properties,null,['class'=>'form-control select2','required','placeholder'=>__('messages.please_select')]) !!}</div></div>
<div class="col-md-3"><div class="form-group">{!! Form::label('hms_room_type_id',__('hms::lang.room_type').':*') !!}<select name="hms_room_type_id" class="form-control select2" required><option value="">{{ __('messages.please_select') }}</option>@foreach($roomTypes as $roomType)<option value="{{ $roomType->id }}">{{ optional($roomType->property)->name }} — {{ $roomType->type }}</option>@endforeach</select></div></div>
<div class="col-md-3"><div class="form-group">{!! Form::label('name',__('hms::lang.name').':*') !!}{!! Form::text('name',null,['class'=>'form-control','required']) !!}</div></div>
<div class="col-md-3"><div class="form-group">{!! Form::label('code',__('hms::lang.code').':*') !!}{!! Form::text('code',null,['class'=>'form-control','required']) !!}</div></div>
<div class="col-md-2"><div class="form-group">{!! Form::label('meal_plan',__('hms::lang.meal_plan').':*') !!}{!! Form::select('meal_plan',['room_only'=>__('hms::lang.room_only'),'breakfast'=>__('hms::lang.breakfast'),'half_board'=>__('hms::lang.half_board'),'full_board'=>__('hms::lang.full_board'),'all_inclusive'=>__('hms::lang.all_inclusive')],null,['class'=>'form-control']) !!}</div></div>
<div class="col-md-2"><div class="form-group">{!! Form::label('base_rate',__('hms::lang.base_rate').':') !!}{!! Form::number('base_rate',null,['class'=>'form-control','step'=>'0.0001','min'=>0]) !!}</div></div>
<div class="col-md-2"><div class="form-group">{!! Form::label('included_adults',__('hms::lang.included_adults').':*') !!}{!! Form::number('included_adults',1,['class'=>'form-control','min'=>1,'max'=>20,'required']) !!}</div></div>
<div class="col-md-2"><div class="form-group">{!! Form::label('included_children',__('hms::lang.included_children').':*') !!}{!! Form::number('included_children',0,['class'=>'form-control','min'=>0,'max'=>20,'required']) !!}</div></div>
<div class="col-md-2"><div class="form-group">{!! Form::label('extra_adult_rate',__('hms::lang.extra_adult_rate').':') !!}{!! Form::number('extra_adult_rate',0,['class'=>'form-control','step'=>'0.0001','min'=>0]) !!}</div></div>
<div class="col-md-2"><div class="form-group">{!! Form::label('extra_child_rate',__('hms::lang.extra_child_rate').':') !!}{!! Form::number('extra_child_rate',0,['class'=>'form-control','step'=>'0.0001','min'=>0]) !!}</div></div>
<div class="col-md-2"><div class="form-group">{!! Form::label('allotment',__('hms::lang.rate_plan_allotment').':') !!}{!! Form::number('allotment',null,['class'=>'form-control','min'=>1]) !!}</div></div>
<div class="col-md-2"><div class="form-group">{!! Form::label('adjustment_type',__('hms::lang.adjustment').':') !!}{!! Form::select('adjustment_type',['fixed'=>__('hms::lang.fixed'),'percentage'=>__('hms::lang.percentage')],null,['class'=>'form-control']) !!}{!! Form::number('adjustment_value',0,['class'=>'form-control','step'=>'0.0001']) !!}</div></div>
<div class="col-md-2"><div class="form-group">{!! Form::label('minimum_stay',__('hms::lang.minimum_stay').':*') !!}{!! Form::number('minimum_stay',1,['class'=>'form-control','min'=>1,'required']) !!}</div></div>
<div class="col-md-2"><div class="form-group">{!! Form::label('maximum_stay',__('hms::lang.maximum_stay').':') !!}{!! Form::number('maximum_stay',null,['class'=>'form-control','min'=>1]) !!}</div></div>
<div class="col-md-2"><div class="form-group">{!! Form::label('deposit_percent',__('hms::lang.deposit_percent').':*') !!}{!! Form::number('deposit_percent',0,['class'=>'form-control','min'=>0,'max'=>100,'step'=>'0.01','required']) !!}<p class="help-block">50% is the recommended reservation guide. Lower or higher policies remain allowed.</p></div></div>
<div class="col-md-2"><div class="form-group">{!! Form::label('minimum_advance_days',__('hms::lang.min_advance_days').':*') !!}{!! Form::number('minimum_advance_days',0,['class'=>'form-control','min'=>0,'required']) !!}</div></div>
<div class="col-md-2"><div class="form-group">{!! Form::label('maximum_advance_days',__('hms::lang.max_advance_days').':') !!}{!! Form::number('maximum_advance_days',null,['class'=>'form-control','min'=>0]) !!}</div></div>
<div class="col-md-2"><div class="form-group">{!! Form::label('free_cancellation_hours',__('hms::lang.free_cancellation_hours').':*') !!}{!! Form::number('free_cancellation_hours',24,['class'=>'form-control','min'=>0,'required']) !!}</div></div>
<div class="col-md-2"><div class="form-group">{!! Form::label('valid_from',__('hms::lang.valid_from').':') !!}{!! Form::date('valid_from',null,['class'=>'form-control']) !!}</div></div>
<div class="col-md-2"><div class="form-group">{!! Form::label('valid_to',__('hms::lang.valid_to').':') !!}{!! Form::date('valid_to',null,['class'=>'form-control']) !!}</div></div>
<div class="col-md-2"><div class="form-group">{!! Form::label('corporate_contact_id',__('hms::lang.corporate_account').':') !!}{!! Form::select('corporate_contact_id',$corporateContacts,null,['class'=>'form-control select2','placeholder'=>__('lang_v1.none')]) !!}</div></div>
<div class="col-md-12"><div class="form-group"><label>@lang('hms::lang.available_weekdays')</label><br>@foreach(['monday','tuesday','wednesday','thursday','friday','saturday','sunday'] as $weekday)<label class="checkbox-inline">{!! Form::checkbox('days_of_week[]',$weekday,true) !!} @lang('hms::lang.'.$weekday)</label>@endforeach</div></div>
<div class="col-md-12"><label class="checkbox-inline">{!! Form::checkbox('is_refundable',1,true) !!} @lang('hms::lang.refundable')</label><label class="checkbox-inline">{!! Form::checkbox('tax_inclusive',1,false) !!} @lang('hms::lang.tax_inclusive')</label><label class="checkbox-inline">{!! Form::checkbox('closed_to_arrival',1,false) !!} @lang('hms::lang.closed_to_arrival')</label><label class="checkbox-inline">{!! Form::checkbox('closed_to_departure',1,false) !!} @lang('hms::lang.closed_to_departure')</label></div>
<div class="col-md-12"><div class="form-group">{!! Form::label('cancellation_policy',__('hms::lang.cancellation_policy').':') !!}{!! Form::textarea('cancellation_policy',null,['class'=>'form-control','rows'=>2]) !!}</div></div>
</div><button class="btn btn-primary"><i class="fa fa-save"></i> @lang('messages.save')</button>{!! Form::close() !!}
</div></div>
<div class="box box-default"><div class="box-body table-responsive"><table class="table table-bordered table-striped"><thead><tr><th>@lang('hms::lang.rate_plan')</th><th>@lang('hms::lang.property')</th><th>@lang('hms::lang.room_type')</th><th>@lang('hms::lang.restrictions')</th><th>@lang('hms::lang.deposit')</th><th>@lang('hms::lang.status')</th><th>@lang('messages.action')</th></tr></thead><tbody>
@forelse($plans as $plan)<tr><td><strong>{{ $plan->name }}</strong><br><small>{{ $plan->code }} / {{ str_replace('_',' ',$plan->meal_plan) }}</small></td><td>{{ optional($plan->property)->name }}</td><td>@foreach($plan->roomTypes as $mapping)<div>{{ optional($mapping->roomType)->type }} — {{ $mapping->base_rate === null ? __('hms::lang.dynamic') : @num_format($mapping->base_rate) }}<br><small>{{ $mapping->included_adults }} @lang('hms::lang.adults') + {{ $mapping->included_children }} @lang('hms::lang.children') · @lang('hms::lang.rate_plan_allotment'): {{ $mapping->allotment ?: __('hms::lang.unlimited') }}</small></div>@endforeach</td><td>{{ $plan->minimum_stay }}–{{ $plan->maximum_stay ?: '∞' }} @lang('hms::lang.nights')</td><td>{{ @num_format($plan->deposit_percent) }}%</td><td><span class="label {{ $plan->is_active ? 'bg-green':'bg-gray' }}">{{ $plan->is_active ? __('hms::lang.active'):__('hms::lang.inactive') }}</span></td><td>{!! Form::open(['route'=>['hms.rate_plans.toggle',$plan->id],'method'=>'post']) !!}<button class="btn btn-xs btn-default">{{ $plan->is_active ? __('hms::lang.deactivate'):__('hms::lang.activate') }}</button>{!! Form::close() !!}</td></tr>@empty<tr><td colspan="7" class="text-center">@lang('hms::lang.no_rate_plans')</td></tr>@endforelse
</tbody></table></div></div>
</section>@endsection
