<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <style>
        body { color:#1f2937; font-family:dejavusans, sans-serif; font-size:10pt; }
        .header { border-bottom:2px solid #0f4c81; margin-bottom:18px; padding-bottom:10px; }
        h1 { color:#0f4c81; font-size:20pt; margin:0; }
        .muted { color:#64748b; }
        .status { background:#eef4f8; border:1px solid #cbd5e1; display:inline-block; padding:4px 8px; }
        table { border-collapse:collapse; margin-top:16px; width:100%; }
        th, td { border:1px solid #cbd5e1; padding:7px; text-align:left; }
        th { background:#eef4f8; }
        .right { text-align:right; }
        .footer { border-top:1px solid #cbd5e1; color:#64748b; font-size:8pt; margin-top:28px; padding-top:8px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Purchase Requisition</h1>
        <div>{{ optional($purchase->business)->name }} · <strong>{{ $purchase->ref_no }}</strong></div>
    </div>
    <table>
        <tr><th>Location</th><td>{{ optional($purchase->location)->name }}</td><th>Status</th><td><span class="status">{{ ucwords(str_replace('_', ' ', optional($purchase->procurementDocument)->approval_status ?: $purchase->status)) }}</span></td></tr>
        <tr><th>Requested by</th><td>{{ optional($purchase->sales_person)->user_full_name }}</td><th>Required by</th><td>{{ $purchase->delivery_date ? \Carbon\Carbon::parse($purchase->delivery_date)->format('d M Y') : '—' }}</td></tr>
        @if(optional($purchase->procurementDocument)->department_id)<tr><th>Department</th><td>{{ optional(optional($purchase->procurementDocument)->department)->name ?: '—' }}</td><th>Priority</th><td>{{ ucfirst($purchase->procurementDocument->priority ?: 'normal') }}</td></tr>@endif
        @if($purchase->additional_notes)<tr><th>Purpose</th><td colspan="3">{{ $purchase->additional_notes }}</td></tr>@endif
    </table>
    <table>
        <thead><tr><th>#</th><th>Product / service</th><th>SKU</th><th class="right">Required quantity</th><th class="right">Remaining</th></tr></thead>
        <tbody>
        @foreach($purchase->purchase_lines as $line)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ optional($line->product)->name }}@if(optional($line->variations)->name) — {{ $line->variations->name }}@endif</td>
                <td>{{ optional($line->product)->sku }}</td>
                <td class="right">{{ number_format((float) $line->quantity, 2) }} {{ optional(optional($line->product)->unit)->short_name }}</td>
                <td class="right">{{ number_format(max(0, (float) $line->quantity - (float) $line->po_quantity_purchased), 2) }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
    <p class="footer">Internal controlled document generated by CashERP. Approval status and audit history in CashERP are authoritative.</p>
</body>
</html>
