@extends('layouts.auth')
@section('title', $property->name)
@section('content')
<div class="container" style="max-width:1000px;margin:30px auto">
    <div class="panel panel-default"><div class="panel-heading"><h2 style="margin:0"><i class="fa fa-hotel"></i> {{ $property->name }}</h2></div><div class="panel-body">
    @if(session('booking_confirmation'))<div class="alert alert-success" role="alert"><h4>@lang('hms::lang.booking_request_received')</h4><p>@lang('hms::lang.booking_reference'): <strong>{{ session('booking_confirmation') }}</strong></p><p>@lang('hms::lang.booking_hold_notice')</p></div>@endif
    {!! Form::open(['route'=>['hms.public_booking.show',$property->public_slug],'method'=>'get','class'=>'form-inline']) !!}<div class="form-group">{!! Form::label('arrival',__('hms::lang.arrival')) !!}{!! Form::date('arrival',$arrival->toDateString(),['class'=>'form-control','required','min'=>now()->toDateString()]) !!}</div><div class="form-group">{!! Form::label('departure',__('hms::lang.departure')) !!}{!! Form::date('departure',$departure->toDateString(),['class'=>'form-control','required']) !!}</div><button class="btn btn-primary">@lang('hms::lang.check_availability')</button>{!! Form::close() !!}
    </div></div>
    <div class="alert alert-info" role="note"><strong>Payment Deposit guidance:</strong> a confirmed reservation will normally request at least 50% of the agreed booking total. You may submit this availability request without payment; the property will confirm its applicable terms. Any refundable Security Deposit is separate and does not count toward the 50%.</div>
    @forelse($roomTypes as $roomType)<div class="panel panel-primary"><div class="panel-heading"><h3 class="panel-title">{{ $roomType->type }}</h3></div><div class="panel-body"><p>{{ strip_tags($roomType->description) }}</p><p><strong>@lang('hms::lang.maximum_occupancy'):</strong> {{ $roomType->max_occupancy }}</p>
    {!! Form::open(['route'=>['hms.public_booking.store',$property->public_slug]]) !!}{!! Form::hidden('room_type_id',$roomType->id) !!}{!! Form::hidden('arrival',$arrival->toDateString()) !!}{!! Form::hidden('departure',$departure->toDateString()) !!}<input type="text" name="website" value="" tabindex="-1" autocomplete="off" style="position:absolute;left:-10000px" aria-hidden="true">
    <div class="row"><div class="col-md-3"><div class="form-group">{!! Form::label('rate_plan_id',__('hms::lang.rate_plan')) !!}{!! Form::select('rate_plan_id',$ratePlansByRoomType[(int) $roomType->id] ?? [],null,['class'=>'form-control','placeholder'=>__('hms::lang.standard_rate')]) !!}</div></div><div class="col-md-2"><div class="form-group">{!! Form::label('adults',__('hms::lang.adults')) !!}{!! Form::number('adults',1,['class'=>'form-control','min'=>1,'max'=>$roomType->no_of_adult,'required']) !!}</div></div><div class="col-md-2"><div class="form-group">{!! Form::label('children',__('hms::lang.children')) !!}{!! Form::number('children',0,['class'=>'form-control','min'=>0,'max'=>$roomType->no_of_child,'required']) !!}</div></div><div class="col-md-5"><div class="form-group">{!! Form::label('name',__('hms::lang.guest_name')) !!}{!! Form::text('name',null,['class'=>'form-control','required','autocomplete'=>'name']) !!}</div></div><div class="col-md-4"><div class="form-group">{!! Form::label('email',__('business.email')) !!}{!! Form::email('email',null,['class'=>'form-control','required','autocomplete'=>'email']) !!}</div></div><div class="col-md-4"><div class="form-group">{!! Form::label('mobile',__('contact.mobile')) !!}{!! Form::text('mobile',null,['class'=>'form-control','required','autocomplete'=>'tel']) !!}</div></div><div class="col-md-4"><div class="form-group">{!! Form::label('preferred_language',__('hms::lang.preferred_language')) !!}{!! Form::text('preferred_language',null,['class'=>'form-control']) !!}</div></div><div class="col-md-12"><div class="form-group">{!! Form::label('special_requests',__('hms::lang.special_requests')) !!}{!! Form::textarea('special_requests',null,['class'=>'form-control','rows'=>2]) !!}</div></div><div class="col-md-12"><label>{!! Form::checkbox('terms_accepted',1,false,['required']) !!} @lang('hms::lang.booking_terms_accept')</label><br><label>{!! Form::checkbox('marketing_consent',1,false) !!} @lang('hms::lang.optional_marketing_consent')</label></div></div><button class="btn btn-success" style="margin-top:15px">@lang('hms::lang.request_booking')</button>{!! Form::close() !!}</div></div>@empty<div class="alert alert-info">@lang('hms::lang.no_rooms_available_for_dates')</div>@endforelse
</div>
@endsection
