@extends('layouts.app')
@section('title', __('hms::lang.channel_manager'))
@section('content')
@include('hms::layouts.nav')
<section class="content-header"><h1>@lang('hms::lang.channel_manager') <small>@lang('hms::lang.channel_manager_help')</small></h1></section>
<section class="content">
<div class="callout callout-info"><p>@lang('hms::lang.channel_adapter_notice')</p></div>
@if(session('hms_channel_secret'))<div class="callout callout-warning"><h4>@lang('hms::lang.copy_channel_secret_now')</h4><code style="word-break:break-all">{{ session('hms_channel_secret') }}</code><p>@lang('hms::lang.channel_secret_once')</p></div>@endif
<div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">@lang('hms::lang.add_channel_connection')</h3></div><div class="box-body">{!! Form::open(['route'=>'hms.channels.store','class'=>'form-inline']) !!}{!! Form::select('hms_property_id',$properties,null,['class'=>'form-control select2','required','placeholder'=>__('hms::lang.property')]) !!}{!! Form::select('provider',['booking_com'=>'Booking.com','expedia'=>'Expedia','airbnb'=>'Airbnb','agoda'=>'Agoda','google_hotel'=>'Google Hotel','custom'=>__('hms::lang.custom')],null,['class'=>'form-control','required']) !!}{!! Form::text('name',null,['class'=>'form-control','required','placeholder'=>__('hms::lang.connection_name')]) !!}<button class="btn btn-primary">@lang('messages.save')</button>{!! Form::close() !!}</div></div>
@foreach($connections as $connection)<div class="box box-default"><div class="box-header with-border"><h3 class="box-title">{{ $connection->name }} <small>{{ ucfirst(str_replace('_',' ',$connection->provider)) }} — {{ optional($connection->property)->name }}</small></h3><span class="label {{ $connection->status === 'active' ? 'bg-green':'bg-gray' }} pull-right">{{ ucfirst($connection->status) }}</span></div><div class="box-body"><p><strong>@lang('hms::lang.webhook_url'):</strong> <code>{{ url('/api/hms/v1/channels/'.$connection->public_key.'/events') }}</code></p><p><strong>@lang('hms::lang.public_key'):</strong> <code>{{ $connection->public_key }}</code></p>
{!! Form::open(['route'=>['hms.channels.rotate',$connection->id],'method'=>'post','style'=>'display:inline']) !!}<button class="btn btn-xs btn-warning" onclick="return confirm('{{ __('hms::lang.confirm_rotate_secret') }}')">@lang('hms::lang.rotate_secret')</button>{!! Form::close() !!}
{!! Form::open(['route'=>['hms.channels.toggle',$connection->id],'method'=>'post','style'=>'display:inline']) !!}<button class="btn btn-xs btn-default">{{ $connection->status === 'active' ? __('hms::lang.pause_webhook'):__('hms::lang.resume_webhook') }}</button>{!! Form::close() !!}
<hr><h4>@lang('hms::lang.inventory_and_rate_mapping')</h4>{!! Form::open(['route'=>['hms.channels.mappings.store',$connection->id],'class'=>'form-inline']) !!}{!! Form::select('local_type',['room_type'=>__('hms::lang.room_type'),'rate_plan'=>__('hms::lang.rate_plan')],null,['class'=>'form-control']) !!}<select name="local_id" class="form-control select2" required><option value="">{{ __('messages.please_select') }}</option><optgroup label="{{ __('hms::lang.room_types') }}">@foreach($roomTypes->where('hms_property_id',$connection->hms_property_id) as $type)<option value="{{ $type->id }}">{{ $type->type }}</option>@endforeach</optgroup><optgroup label="{{ __('hms::lang.rate_plans') }}">@foreach($ratePlans->where('hms_property_id',$connection->hms_property_id) as $plan)<option value="{{ $plan->id }}">{{ $plan->name }}</option>@endforeach</optgroup></select>{!! Form::text('external_id',null,['class'=>'form-control','required','placeholder'=>__('hms::lang.external_id')]) !!}<button class="btn btn-primary">@lang('hms::lang.map')</button>{!! Form::close() !!}
<div class="table-responsive" style="margin-top:15px"><table class="table table-bordered"><thead><tr><th>@lang('hms::lang.local_type')</th><th>@lang('hms::lang.local_id')</th><th>@lang('hms::lang.external_id')</th></tr></thead><tbody>@forelse($connection->mappings as $mapping)<tr><td>{{ $mapping->local_type }}</td><td>{{ $mapping->local_id }}</td><td>{{ $mapping->external_id }}</td></tr>@empty<tr><td colspan="3">@lang('hms::lang.no_channel_mappings')</td></tr>@endforelse</tbody></table></div>
<hr><h4>@lang('hms::lang.recent_channel_events')</h4><div class="table-responsive"><table class="table table-bordered table-condensed"><thead><tr><th>@lang('hms::lang.received_at')</th><th>@lang('hms::lang.event')</th><th>@lang('hms::lang.external_id')</th><th>@lang('hms::lang.signature')</th><th>@lang('hms::lang.status')</th><th>@lang('hms::lang.last_error')</th></tr></thead><tbody>@forelse($connection->messages as $message)<tr><td>{{ @format_datetime($message->created_at) }}</td><td>{{ $message->event_type }}</td><td>{{ $message->external_event_id }}</td><td>{{ $message->signature_valid ? __('hms::lang.valid'):__('hms::lang.invalid') }}</td><td>{{ ucfirst($message->status) }}</td><td>{{ $message->last_error ? \Illuminate\Support\Str::limit($message->last_error,120) : '-' }}</td></tr>@empty<tr><td colspan="6">@lang('hms::lang.no_channel_events')</td></tr>@endforelse</tbody></table></div>
</div></div>@endforeach
</section>@endsection
