@extends('layouts.app')
@section('title', __('hms::lang.night_audit'))
@section('content')
@include('hms::layouts.nav')
<section class="content-header"><h1>@lang('hms::lang.night_audit') <small>@lang('hms::lang.night_audit_help')</small></h1></section>
<section class="content">
<div class="box box-default"><div class="box-body">{!! Form::open(['route'=>'hms.night_audit.index','method'=>'get','class'=>'form-inline']) !!}{!! Form::label('property_id',__('hms::lang.property').':') !!}{!! Form::select('property_id',$properties,$propertyId,['class'=>'form-control select2','required']) !!}<button class="btn btn-primary">@lang('hms::lang.review')</button>{!! Form::close() !!}</div></div>
@if($preview)<div class="row"><div class="col-md-3"><div class="info-box"><span class="info-box-icon bg-blue"><i class="fa fa-calendar"></i></span><div class="info-box-content"><span class="info-box-text">@lang('hms::lang.business_date')</span><span class="info-box-number">{{ $preview['business_date'] }}</span></div></div></div><div class="col-md-3"><div class="info-box"><span class="info-box-icon bg-green"><i class="fa fa-money"></i></span><div class="info-box-content"><span class="info-box-text">@lang('hms::lang.room_revenue')</span><span class="info-box-number">{{ @num_format($preview['summary']['room_revenue']) }}</span></div></div></div><div class="col-md-3"><div class="info-box"><span class="info-box-icon bg-aqua"><i class="fa fa-bed"></i></span><div class="info-box-content"><span class="info-box-text">@lang('hms::lang.occupancy')</span><span class="info-box-number">{{ $preview['summary']['occupancy_percent'] }}%</span></div></div></div><div class="col-md-3"><div class="info-box"><span class="info-box-icon {{ $preview['has_blocking_exceptions'] ? 'bg-red':'bg-green' }}"><i class="fa fa-exclamation-triangle"></i></span><div class="info-box-content"><span class="info-box-text">@lang('hms::lang.blockers')</span><span class="info-box-number">{{ array_sum($preview['exceptions']) }}</span></div></div></div></div>
<div class="box {{ $preview['has_blocking_exceptions'] ? 'box-danger':'box-success' }}"><div class="box-header with-border"><h3 class="box-title">@lang('hms::lang.pre_close_review')</h3></div><div class="box-body"><div class="row">@foreach($preview['exceptions'] as $name=>$count)<div class="col-md-3"><strong>{{ ucwords(str_replace('_',' ',$name)) }}</strong><div>{{ $count }}</div></div>@endforeach</div><hr>{!! Form::open(['route'=>'hms.night_audit.close']) !!}{!! Form::hidden('property_id',$propertyId) !!}@if(auth()->user()->can('superadmin') || auth()->user()->can('hms.override_night_audit'))<label>{!! Form::checkbox('override',1,false) !!} @lang('hms::lang.authorized_override')</label>{!! Form::text('override_reason',null,['class'=>'form-control','placeholder'=>__('hms::lang.override_reason')]) !!}@endif<button class="btn btn-danger" onclick="return confirm('{{ __('hms::lang.confirm_night_audit') }}')">@lang('hms::lang.close_business_date')</button>{!! Form::close() !!}</div></div>@endif
<div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">@lang('hms::lang.cashier_shifts')</h3></div><div class="box-body">{!! Form::open(['route'=>'hms.cashier_shifts.open','class'=>'form-inline']) !!}{!! Form::select('property_id',$properties,$propertyId,['class'=>'form-control select2','required']) !!}{!! Form::number('opening_float',0,['class'=>'form-control','min'=>0,'step'=>'0.0001','required','placeholder'=>__('hms::lang.opening_float')]) !!}<button class="btn btn-primary">@lang('hms::lang.open_shift')</button>{!! Form::close() !!}<hr><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>@lang('hms::lang.property')</th><th>@lang('hms::lang.cashier')</th><th>@lang('hms::lang.opened_at')</th><th>@lang('hms::lang.expected_cash')</th><th>@lang('hms::lang.variance')</th><th>@lang('hms::lang.status')</th><th>@lang('messages.action')</th></tr></thead><tbody>@forelse($shifts as $shift)<tr><td>{{ optional($shift->property)->name }}</td><td>{{ optional($shift->user)->user_full_name }}</td><td>{{ @format_datetime($shift->opened_at) }}</td><td>{{ @num_format($shift->expected_cash) }}</td><td>{{ $shift->variance === null ? '-' : @num_format($shift->variance) }}</td><td>{{ ucfirst($shift->status) }}</td><td>@if($shift->status==='open' && $shift->user_id===auth()->id()){!! Form::open(['route'=>['hms.cashier_shifts.close',$shift->id],'class'=>'form-inline']) !!}{!! Form::number('declared_cash',null,['class'=>'form-control input-sm','required','min'=>0,'step'=>'0.0001','placeholder'=>__('hms::lang.declared_cash')]) !!}{!! Form::text('variance_reason',null,['class'=>'form-control input-sm','placeholder'=>__('hms::lang.variance_reason')]) !!}<button class="btn btn-xs btn-warning">@lang('hms::lang.close_shift')</button>{!! Form::close() !!}@endif</td></tr>@empty<tr><td colspan="7">@lang('hms::lang.no_cashier_shifts')</td></tr>@endforelse</tbody></table></div></div></div>
<div class="box box-default"><div class="box-header with-border"><h3 class="box-title">@lang('hms::lang.audit_history')</h3></div><div class="box-body table-responsive"><table class="table table-bordered"><thead><tr><th>@lang('hms::lang.property')</th><th>@lang('hms::lang.business_date')</th><th>@lang('hms::lang.closed_at')</th><th>@lang('hms::lang.override')</th><th>@lang('hms::lang.summary')</th></tr></thead><tbody>@forelse($audits as $audit)<tr><td>{{ optional($audit->property)->name }}</td><td>{{ optional($audit->business_date)->toDateString() }}</td><td>{{ @format_datetime($audit->closed_at) }}</td><td>{{ $audit->override_used ? __('messages.yes'):__('messages.no') }}</td><td>{{ __('hms::lang.room_revenue') }}: {{ @num_format($audit->summary['room_revenue'] ?? 0) }}, {{ __('hms::lang.occupancy') }}: {{ $audit->summary['occupancy_percent'] ?? 0 }}%</td></tr>@empty<tr><td colspan="5">@lang('hms::lang.no_night_audits')</td></tr>@endforelse</tbody></table></div></div>
</section>@endsection
