@extends('layouts.app')
@section('title', __('hms::lang.revenue_management'))
@section('content')
@include('hms::layouts.nav')
<section class="content-header"><h1>@lang('hms::lang.revenue_management') <small>@lang('hms::lang.revenue_management_help')</small></h1></section>
<section class="content"><div class="box box-default"><div class="box-body">{!! Form::open(['route'=>'hms.revenue.index','method'=>'get','class'=>'form-inline']) !!}{!! Form::select('property_id',$properties,$propertyId,['class'=>'form-control select2','required']) !!}{!! Form::date('start_date',$start->toDateString(),['class'=>'form-control','required']) !!}{!! Form::date('end_date',$end->toDateString(),['class'=>'form-control','required']) !!}<button class="btn btn-primary">@lang('hms::lang.apply')</button>{!! Form::close() !!}</div></div>
@if($metrics)<div class="row">@foreach(['occupancy_percent'=>__('hms::lang.occupancy_percent'),'adr'=>__('hms::lang.adr'),'revpar'=>__('hms::lang.revpar'),'room_revenue'=>__('hms::lang.room_revenue'),'sold_room_nights'=>__('hms::lang.sold_room_nights'),'cancellation_percent'=>__('hms::lang.cancellation_percent')] as $key=>$label)<div class="col-md-2 col-sm-4"><div class="info-box"><span class="info-box-icon bg-blue"><i class="fa fa-line-chart"></i></span><div class="info-box-content"><span class="info-box-text">{{ $label }}</span><span class="info-box-number">{{ in_array($key,['occupancy_percent','cancellation_percent']) ? $metrics[$key].'%' : @num_format($metrics[$key]) }}</span></div></div></div>@endforeach</div>
<div class="row"><div class="col-md-7"><div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">@lang('hms::lang.channel_performance')</h3></div><div class="box-body table-responsive"><table class="table table-bordered"><thead><tr><th>@lang('hms::lang.booking_source')</th><th>@lang('hms::lang.bookings')</th><th>@lang('hms::lang.revenue')</th></tr></thead><tbody>@forelse($metrics['by_source'] as $source=>$row)<tr><td>{{ ucwords(str_replace('_',' ',$source)) }}</td><td>{{ $row['bookings'] }}</td><td>{{ @num_format($row['revenue']) }}</td></tr>@empty<tr><td colspan="3">@lang('hms::lang.no_data')</td></tr>@endforelse</tbody></table></div></div></div><div class="col-md-5"><div class="box box-default"><div class="box-header with-border"><h3 class="box-title">@lang('hms::lang.monthly_budget')</h3></div><div class="box-body">{!! Form::open(['route'=>'hms.revenue.budget']) !!}{!! Form::hidden('property_id',$propertyId) !!}{!! Form::hidden('month',$start->copy()->startOfMonth()->toDateString()) !!}<div class="form-group">{!! Form::label('room_revenue_budget',__('hms::lang.room_revenue_budget')) !!}{!! Form::number('room_revenue_budget',$budget->room_revenue_budget ?? 0,['class'=>'form-control','min'=>0,'step'=>'0.0001']) !!}</div><div class="form-group">{!! Form::label('occupancy_budget',__('hms::lang.occupancy_budget')) !!}{!! Form::number('occupancy_budget',$budget->occupancy_budget ?? 0,['class'=>'form-control','min'=>0,'max'=>100,'step'=>'0.01']) !!}</div><div class="form-group">{!! Form::label('adr_budget',__('hms::lang.adr_budget')) !!}{!! Form::number('adr_budget',$budget->adr_budget ?? 0,['class'=>'form-control','min'=>0,'step'=>'0.0001']) !!}</div><button class="btn btn-primary">@lang('messages.save')</button>{!! Form::close() !!}</div></div></div></div>@endif
</section>@endsection
