@extends('layouts.app')
@section('title', __('hms::lang.group_bookings'))
@section('content')
@include('hms::layouts.nav')
<section class="content-header"><h1>@lang('hms::lang.group_bookings') <small>@lang('hms::lang.group_bookings_help')</small></h1></section>
<section class="content">
<div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">@lang('hms::lang.add_group')</h3></div><div class="box-body">
{!! Form::open(['route'=>'hms.groups.store']) !!}<div class="row">
<div class="col-md-3"><div class="form-group">{!! Form::label('name',__('hms::lang.group_name').':*') !!}{!! Form::text('name',null,['class'=>'form-control','required']) !!}</div></div>
<div class="col-md-2"><div class="form-group">{!! Form::label('code',__('hms::lang.code').':*') !!}{!! Form::text('code',null,['class'=>'form-control','required']) !!}</div></div>
<div class="col-md-2"><div class="form-group">{!! Form::label('hms_property_id',__('hms::lang.property').':*') !!}{!! Form::select('hms_property_id',$properties,null,['class'=>'form-control select2','required']) !!}</div></div>
<div class="col-md-3"><div class="form-group">{!! Form::label('organizer_contact_id',__('hms::lang.organizer').':') !!}{!! Form::select('organizer_contact_id',$contacts,null,['class'=>'form-control select2','placeholder'=>__('lang_v1.none')]) !!}</div></div>
<div class="col-md-2"><div class="form-group">{!! Form::label('status',__('hms::lang.status').':*') !!}{!! Form::select('status',['tentative'=>__('hms::lang.tentative'),'confirmed'=>__('hms::lang.confirmed')],null,['class'=>'form-control']) !!}</div></div>
<div class="col-md-3"><div class="form-group">{!! Form::label('arrival_at',__('hms::lang.arrival').':*') !!}<input type="datetime-local" name="arrival_at" class="form-control" required></div></div>
<div class="col-md-3"><div class="form-group">{!! Form::label('departure_at',__('hms::lang.departure').':*') !!}<input type="datetime-local" name="departure_at" class="form-control" required></div></div>
<div class="col-md-3"><div class="form-group">{!! Form::label('release_at',__('hms::lang.release_at').':') !!}<input type="datetime-local" name="release_at" class="form-control"></div></div>
<div class="col-md-3"><div class="form-group">{!! Form::label('billing_instruction',__('hms::lang.billing_instruction').':*') !!}{!! Form::select('billing_instruction',['individual'=>__('hms::lang.individual_billing'),'master'=>__('hms::lang.master_folio'),'split'=>__('hms::lang.split_billing')],null,['class'=>'form-control']) !!}</div></div>
<div class="col-md-3"><div class="form-group">{!! Form::label('deposit_required',__('hms::lang.deposit_required').':') !!}{!! Form::number('deposit_required',0,['class'=>'form-control','min'=>0,'step'=>'0.0001']) !!}<p class="help-block">Advisory: request at least 50% of the expected group value before confirmation. This is guidance, not validation. Refundable Security Deposit is separate.</p></div></div>
<div class="col-md-9"><div class="form-group">{!! Form::label('notes',__('hms::lang.notes').':') !!}{!! Form::text('notes',null,['class'=>'form-control','maxlength'=>5000]) !!}</div></div>
</div><button class="btn btn-primary">@lang('messages.save')</button>{!! Form::close() !!}</div></div>
@foreach($groups as $group)<div class="box box-default"><div class="box-header with-border"><h3 class="box-title">{{ $group->name }} <small>{{ $group->code }} — {{ optional($group->property)->name }}</small></h3><span class="label {{ $group->status === 'confirmed' ? 'bg-green':'bg-yellow' }} pull-right">{{ ucfirst($group->status) }}</span></div><div class="box-body">
<p>{{ @format_datetime($group->arrival_at) }} → {{ @format_datetime($group->departure_at) }} | @lang('hms::lang.pickup'): {{ $group->roomBlocks->where('status','picked_up')->count() }}/{{ $group->roomBlocks->whereIn('status',['held','picked_up'])->count() }} @if($group->folio)| <a href="{{ route('hms.folios.show',$group->folio->id) }}">@lang('hms::lang.master_folio'): {{ $group->folio->folio_number }}</a>@endif</p>
{!! Form::open(['route'=>['hms.groups.blocks.store',$group->id],'class'=>'form-inline']) !!}<div class="form-group"><select name="hms_room_id" class="form-control select2" required><option value="">{{ __('hms::lang.select_room') }}</option>@foreach($rooms->where('hms_property_id',$group->hms_property_id) as $room)<option value="{{ $room->id }}">{{ $room->room_number }} — {{ optional($room->type)->type }}</option>@endforeach</select></div><div class="form-group">{!! Form::number('agreed_rate',null,['class'=>'form-control','min'=>0,'step'=>'0.0001','placeholder'=>__('hms::lang.agreed_rate')]) !!}</div><button class="btn btn-primary">@lang('hms::lang.hold_room')</button>{!! Form::close() !!}
<div class="table-responsive" style="margin-top:15px"><table class="table table-bordered"><thead><tr><th>@lang('hms::lang.room')</th><th>@lang('hms::lang.agreed_rate')</th><th>@lang('hms::lang.release_at')</th><th>@lang('hms::lang.status')</th><th>@lang('hms::lang.booking_reference')</th><th>@lang('messages.action')</th></tr></thead><tbody>@forelse($group->roomBlocks as $block)<tr><td>{{ optional($block->room)->room_number }}</td><td>{{ $block->agreed_rate === null ? '-' : @num_format($block->agreed_rate) }}</td><td>{{ $block->release_at ? @format_datetime($block->release_at) : '-' }}</td><td>{{ ucfirst($block->status) }}</td><td>{{ optional($block->booking)->ref_no ?: '-' }}</td><td>@if($block->status === 'held'){!! Form::open(['route'=>['hms.groups.blocks.release',$block->id],'method'=>'post']) !!}<button class="btn btn-xs btn-warning">@lang('hms::lang.release')</button>{!! Form::close() !!}@endif</td></tr>@empty<tr><td colspan="6" class="text-center">@lang('hms::lang.no_room_blocks')</td></tr>@endforelse</tbody></table></div>
</div></div>@endforeach
</section>@endsection
