@extends('layouts.app')
@section('title','Workforce Analytics')
@section('content')
@include('essentials::layouts.nav_hrm')
<section class="content-header"><h1>Workforce Analytics <small>Company-scoped metrics calculated from source records</small></h1></section>
<section class="content">
    @component('components.widget',['class'=>'box-primary','title'=>'Reporting period'])
        {!! Form::open(['method'=>'GET','route'=>'hrm.analytics.index','class'=>'row']) !!}<div class="col-md-3"><div class="form-group">{!! Form::label('start','Start date *') !!}{!! Form::date('start',$start,['class'=>'form-control','required']) !!}</div></div><div class="col-md-3"><div class="form-group">{!! Form::label('end','End date *') !!}{!! Form::date('end',$end,['class'=>'form-control','required']) !!}</div></div><div class="col-md-2"><label>&nbsp;</label><button class="btn btn-primary btn-block"><i class="fa fa-refresh"></i> Recalculate</button></div><div class="col-md-2"><label>&nbsp;</label><a class="btn btn-default btn-block" href="{{route('hrm.analytics.export',['start'=>$start,'end'=>$end])}}"><i class="fa fa-download"></i> Export CSV</a></div>{!! Form::close() !!}
        <p class="text-muted small">Every number below is calculated from this company’s current HR records. Historical trend data appears only after the scheduled daily snapshot command has run.</p>
    @endcomponent
    <div class="row">
        @php($labels=['headcount'=>'Headcount','new_hires'=>'New hires','terminations'=>'Terminations','turnover_rate'=>'Turnover rate %','approved_absence_days'=>'Approved absence days','learning_completion_rate'=>'Learning completion %','posted_payroll_net'=>'Posted payroll net','pending_time_corrections'=>'Pending time corrections','documents_expiring_60_days'=>'Documents expiring in 60 days','open_requisitions'=>'Open positions'])
        @foreach($metrics as $key=>$metric)<div class="col-md-3 col-sm-6"><div class="info-box"><span class="info-box-icon bg-aqua"><i class="fa fa-line-chart"></i></span><div class="info-box-content"><span class="info-box-text">{{$labels[$key] ?? ucwords(str_replace('_',' ',$key))}}</span><span class="info-box-number">{{is_numeric($metric['value']) ? number_format($metric['value'],in_array($key,['turnover_rate','learning_completion_rate','posted_payroll_net'])?2:0) : $metric['value']}}</span><small>Population: {{$metric['population']===null?'Not applicable':$metric['population']}}</small></div></div></div>@endforeach
    </div>
    <div class="row"><div class="col-md-6">@component('components.widget',['title'=>'Headcount by department'])<p class="text-muted small">Groups under five employees are combined and suppressed to reduce re-identification risk.</p><table class="table table-bordered table-striped"><thead><tr><th>Department</th><th class="text-right">Employees</th><th>Privacy</th></tr></thead><tbody>@forelse($departments as $row)<tr><td>{{$row['department']}}</td><td class="text-right">{{$row['employee_count']}}</td><td>{{$row['suppressed']?'Suppressed':'Reportable'}}</td></tr>@empty<tr><td colspan="3" class="text-muted text-center">No active employees.</td></tr>@endforelse</tbody></table>@endcomponent</div><div class="col-md-6">@component('components.widget',['title'=>'Historical snapshots'])<table class="table table-condensed"><thead><tr><th>Metric</th><th>Snapshot count</th><th>Latest value</th><th>Latest date</th></tr></thead><tbody>@forelse($history as $key=>$rows)@php($latest=$rows->last())<tr><td>{{$labels[$key] ?? ucwords(str_replace('_',' ',$key))}}</td><td>{{$rows->count()}}</td><td>{{number_format($latest->metric_value,2)}}</td><td>{{$latest->snapshot_date}}</td></tr>@empty<tr><td colspan="4" class="text-muted text-center">No snapshots yet. The scheduler creates them daily at 00:20.</td></tr>@endforelse</tbody></table>@endcomponent</div></div>
    <div class="callout callout-info"><h4>Responsible analytics</h4><p>CashERP reports operational HR metrics, not automated employment decisions. Sensitive diversity or medical data is not used for ranking, pay, discipline, recruitment, or performance scoring. Country-specific equality, retention and reporting obligations still require local professional review.</p></div>
</section>
@endsection
