@extends('layouts.app')
@section('title', __('hms::lang.hotel_services'))
@section('content')
@include('hms::layouts.nav')
<section class="content-header"><h1>@lang('hms::lang.hotel_services') <small>@lang('hms::lang.hotel_services_help')</small></h1></section>
<section class="content"><div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">@lang('hms::lang.new_operational_task')</h3></div><div class="box-body">{!! Form::open(['route'=>'hms.operations.store']) !!}<div class="row">
<div class="col-md-2"><div class="form-group">{!! Form::label('hms_property_id',__('hms::lang.property').':*') !!}{!! Form::select('hms_property_id',$properties,null,['class'=>'form-control select2','required']) !!}</div></div>
<div class="col-md-2"><div class="form-group">{!! Form::label('hms_room_id',__('hms::lang.room').':') !!}<select name="hms_room_id" class="form-control select2"><option value="">{{ __('lang_v1.none') }}</option>@foreach($rooms as $room)<option value="{{ $room->id }}">{{ optional($room->property)->name }} {{ $room->room_number }} — {{ optional($room->type)->type }}</option>@endforeach</select></div></div>
<div class="col-md-2"><div class="form-group">{!! Form::label('transaction_id',__('hms::lang.booking').':') !!}{!! Form::select('transaction_id',$bookings,null,['class'=>'form-control select2','placeholder'=>__('lang_v1.none')]) !!}</div></div>
<div class="col-md-2"><div class="form-group">{!! Form::label('task_type',__('hms::lang.task_type').':*') !!}{!! Form::select('task_type',['maintenance'=>__('hms::lang.maintenance'),'out_of_order'=>__('hms::lang.out_of_order'),'minibar'=>__('hms::lang.minibar'),'linen'=>__('hms::lang.linen'),'laundry'=>__('hms::lang.laundry'),'turndown'=>__('hms::lang.turndown'),'guest_request'=>__('hms::lang.guest_request'),'lost_found'=>__('hms::lang.lost_and_found')],null,['class'=>'form-control','required']) !!}</div></div>
<div class="col-md-2"><div class="form-group">{!! Form::label('priority',__('hms::lang.priority').':*') !!}{!! Form::select('priority',['low'=>__('hms::lang.low'),'normal'=>__('hms::lang.normal'),'high'=>__('hms::lang.high'),'urgent'=>__('hms::lang.urgent')],'normal',['class'=>'form-control']) !!}</div></div>
<div class="col-md-2"><div class="form-group">{!! Form::label('assigned_to',__('hms::lang.assigned_to').':') !!}{!! Form::select('assigned_to',$staff,null,['class'=>'form-control select2','placeholder'=>__('lang_v1.none')]) !!}</div></div>
<div class="col-md-3"><div class="form-group">{!! Form::label('item_name',__('hms::lang.item_name').':') !!}{!! Form::text('item_name',null,['class'=>'form-control']) !!}</div></div><div class="col-md-2"><div class="form-group">{!! Form::label('quantity',__('hms::lang.quantity').':') !!}{!! Form::number('quantity',null,['class'=>'form-control','min'=>0,'step'=>'0.0001']) !!}</div></div><div class="col-md-2"><div class="form-group">{!! Form::label('charge_amount',__('hms::lang.guest_charge').':') !!}{!! Form::number('charge_amount',0,['class'=>'form-control','min'=>0,'step'=>'0.0001']) !!}</div></div><div class="col-md-2"><div class="form-group">{!! Form::label('due_at',__('hms::lang.due_at').':') !!}<input type="datetime-local" name="due_at" class="form-control"></div></div><div class="col-md-3"><div class="form-group">{!! Form::label('custody_reference',__('hms::lang.custody_reference').':') !!}{!! Form::text('custody_reference',null,['class'=>'form-control']) !!}</div></div>
<div class="col-md-12"><div class="form-group">{!! Form::label('description',__('hms::lang.description').':*') !!}{!! Form::textarea('description',null,['class'=>'form-control','rows'=>2,'required']) !!}</div></div>
</div><button class="btn btn-primary">@lang('messages.save')</button>{!! Form::close() !!}</div></div>
<div class="box box-default"><div class="box-header with-border"><h3 class="box-title">@lang('hms::lang.operational_tasks')</h3></div><div class="box-body table-responsive"><table class="table table-bordered table-striped"><thead><tr><th>@lang('hms::lang.created_at')</th><th>@lang('hms::lang.property')</th><th>@lang('hms::lang.room')</th><th>@lang('hms::lang.task_type')</th><th>@lang('hms::lang.description')</th><th>@lang('hms::lang.status')</th><th>@lang('messages.action')</th></tr></thead><tbody>@forelse($tasks as $task)<tr><td>{{ @format_datetime($task->occurred_at) }}</td><td>{{ optional($task->property)->name }}</td><td>{{ optional($task->room)->room_number ?: '-' }}</td><td>{{ ucwords(str_replace('_',' ',$task->task_type)) }}<br><small>{{ ucfirst($task->priority) }}</small></td><td>{{ $task->description }}@if($task->charge_amount>0)<br><span class="label bg-blue">{{ @num_format($task->charge_amount) }}</span>@endif</td><td>{{ ucfirst(str_replace('_',' ',$task->status)) }}</td><td>@if(!in_array($task->status,['resolved','cancelled'])){!! Form::open(['route'=>['hms.operations.transition',$task->id],'class'=>'form-inline']) !!}{!! Form::select('status',['assigned'=>__('hms::lang.assigned'),'in_progress'=>__('hms::lang.in_progress'),'resolved'=>__('hms::lang.resolved'),'cancelled'=>__('hms::lang.cancelled')],$task->status,['class'=>'form-control input-sm']) !!}{!! Form::text('notes',null,['class'=>'form-control input-sm','placeholder'=>__('hms::lang.resolution_notes')]) !!}<button class="btn btn-xs btn-primary">@lang('messages.update')</button>{!! Form::close() !!}@endif</td></tr>@empty<tr><td colspan="7">@lang('hms::lang.no_operational_tasks')</td></tr>@endforelse</tbody></table><div class="pull-right">{{ $tasks->links() }}</div></div></div>
</section>@endsection
