@extends('layouts.app')
@section('title','Security Deposit Alerts')
@section('content')
<section class="content-header"><h1>Refundable Security Deposit Register <small>Property leases and uncleared alerts</small></h1></section>
<section class="content">
<div class="callout callout-info"><h4>Separate from rent and income</h4><p>This register holds refundable security deposits only. Payment Deposits (Advances) are managed inside each lease and reduce rent balances.</p></div>
@if($alerts->isNotEmpty())<div class="box box-warning"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-bell"></i> Pending and uncleared alerts</h3></div><div class="box-body table-responsive"><table class="table table-condensed"><thead><tr><th>Alert</th><th>Transaction</th><th>Client</th><th>Status</th><th>Held</th><th></th></tr></thead><tbody>@foreach($alerts as $alert)<tr><td><span class="label label-{{ $alert['severity'] }}">{{ $alert['reason'] }}</span></td><td>Lease #{{ $alert['deposit']->context_id }}<br><small>{{ optional($alert['deposit']->location)->name }}</small></td><td>{{ optional($alert['deposit']->contact)->name }}</td><td>{{ ucfirst(str_replace('_',' ',$alert['deposit']->status)) }}</td><td class="display_currency" data-currency_symbol="true">{{ $alert['deposit']->held_balance }}</td><td><a class="btn btn-xs btn-primary" href="{{ route('property.deposits.show',$alert['deposit']->context_id) }}">Review</a></td></tr>@endforeach</tbody></table></div></div>@endif
<div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">All lease security deposits</h3></div><div class="box-body table-responsive"><table class="table table-bordered table-striped"><thead><tr><th>Lease transaction</th><th>Tenant</th><th>Required</th><th>Received</th><th>Damage</th><th>Refunded</th><th>Held</th><th>Status</th><th></th></tr></thead><tbody>@forelse($deposits as $deposit)<tr><td>Lease #{{ $deposit->context_id }}<br><small>{{ optional($deposit->location)->name }}</small></td><td>{{ optional($deposit->contact)->name }}</td><td class="display_currency" data-currency_symbol="true">{{ $deposit->required_amount }}</td><td class="display_currency" data-currency_symbol="true">{{ $deposit->received_amount }}</td><td class="display_currency" data-currency_symbol="true">{{ $deposit->damage_amount }}</td><td class="display_currency" data-currency_symbol="true">{{ $deposit->refunded_amount }}</td><td class="display_currency" data-currency_symbol="true">{{ $deposit->held_balance }}</td><td>{{ ucfirst(str_replace('_',' ',$deposit->status)) }}</td><td><a class="btn btn-xs btn-primary" href="{{ route('property.deposits.show',$deposit->context_id) }}">Open</a></td></tr>@empty<tr><td colspan="9" class="text-center text-muted">No refundable security deposits are configured.</td></tr>@endforelse</tbody></table></div><div class="box-footer">{{ $deposits->links() }}</div></div>
</section>
@endsection
