@extends('layouts.app')
@section('title','Lease Deposits')
@section('content')
<section class="content-header"><h1>Lease Deposits <small>{{ optional(optional($model->unit)->property)->name }} / {{ optional($model->unit)->unit_code }} — {{ optional($model->tenant)->name }}</small></h1></section>
<section class="content">
<div class="row"><div class="col-md-6"><div class="callout callout-warning"><h4>Security Deposit — refundable, not income</h4><p>Held for risk. It does not reduce rent and never posts to revenue, tax or the invoice-payment total. At lease end, record damage and refund the balance.</p></div></div><div class="col-md-6"><div class="callout callout-info"><h4>Payment Deposit — advance payment</h4><p>Belongs toward rent. It is automatically applied to the earliest outstanding or future generated rent and follows normal payment/accounting logic.</p></div></div></div>
@if($securityDeposit)
<div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">Refundable security deposit</h3><span class="label label-{{ in_array($securityDeposit->status,['settled','waived'])?'success':($securityDeposit->status==='excess_due'?'danger':'warning') }} pull-right">{{ ucfirst(str_replace('_',' ',$securityDeposit->status)) }}</span></div><div class="box-body">
<div class="row">@foreach([['Required',$securityDeposit->required_amount],['Received',$securityDeposit->received_amount],['Damage',$securityDeposit->damage_amount],['Refunded',$securityDeposit->refunded_amount],['Held / refundable',$securityDeposit->held_balance],['Excess damage due',$securityDeposit->excess_damage_amount]] as $stat)<div class="col-sm-2"><strong>{{ $stat[0] }}</strong><br><span class="display_currency" data-currency_symbol="true">{{ $stat[1] }}</span></div>@endforeach</div><hr>
@if(auth()->user()->can('property.deposit.manage') || auth()->user()->can('superadmin') || auth()->user()->hasRole('Admin#'.session('user.business_id')))
{!! Form::open(['route'=>['property.deposits.requirement',$model],'method'=>'put','class'=>'row']) !!}<div class="col-sm-3 form-group"><label>Required amount</label><input type="number" name="required_amount" value="{{ $securityDeposit->required_amount }}" min="0" step="0.0001" class="form-control" required></div><div class="col-sm-3 form-group"><label>Due date</label><input type="date" name="due_date" value="{{ optional($securityDeposit->due_date)->toDateString() }}" class="form-control"></div><div class="col-sm-4 form-group"><label>Refund terms</label><input name="terms" value="{{ $securityDeposit->terms }}" class="form-control" maxlength="5000"></div><div class="col-sm-2 form-group"><label>&nbsp;</label><button class="btn btn-default btn-block">Update</button></div>{!! Form::close() !!}
<div class="row"><div class="col-md-4"><h4>Receive security deposit</h4>{!! Form::open(['route'=>['property.deposits.receipt',$model]]) !!}<input type="hidden" name="idempotency_key" value="{{ Str::uuid() }}"><div class="form-group"><input type="number" name="amount" min="0.0001" step="0.0001" class="form-control" required placeholder="Amount"></div><div class="form-group"><input type="date" name="occurred_on" value="{{ now()->toDateString() }}" class="form-control" required></div><div class="form-group">{!! Form::select('payment_method',$paymentMethods,null,['class'=>'form-control','required','placeholder'=>'Payment method']) !!}</div><div class="form-group"><input name="reference" class="form-control" maxlength="191" placeholder="Reference"></div><button class="btn btn-success">Record held funds</button>{!! Form::close() !!}</div>
<div class="col-md-4"><h4>Assess damage</h4>{!! Form::open(['route'=>['property.deposits.damage',$model],'files'=>true]) !!}<div class="form-group"><input type="number" name="amount" min="0.0001" step="0.0001" class="form-control" required placeholder="Assessed amount"></div><div class="form-group"><input type="date" name="occurred_on" value="{{ now()->toDateString() }}" class="form-control" required></div><div class="form-group"><textarea name="description" class="form-control" required minlength="5" maxlength="3000" placeholder="Damage/loss and assessment basis"></textarea></div><div class="form-group"><input type="file" name="evidence" accept=".jpg,.jpeg,.png,.pdf" class="form-control"></div><button class="btn btn-warning">Record assessment</button>{!! Form::close() !!}</div>
<div class="col-md-4"><h4>Request refund</h4>{!! Form::open(['route'=>['property.deposits.refund',$model]]) !!}<input type="hidden" name="idempotency_key" value="{{ Str::uuid() }}"><div class="form-group"><input type="number" name="amount" min="0.0001" max="{{ $securityDeposit->available_refund }}" step="0.0001" class="form-control" required placeholder="Refund amount"></div><div class="form-group"><input type="date" name="occurred_on" value="{{ now()->toDateString() }}" class="form-control" required></div><div class="form-group">{!! Form::select('payment_method',$paymentMethods,null,['class'=>'form-control','required','placeholder'=>'Refund method']) !!}</div><div class="form-group"><input name="reference" class="form-control" maxlength="191" placeholder="Refund reference"></div><button class="btn btn-primary">Submit for approval</button>{!! Form::close() !!}@if($securityDeposit->received_amount<=0 && !in_array($securityDeposit->status,['waived','settled']))<hr>{!! Form::open(['route'=>['property.deposits.waive',$model]]) !!}<input name="reason" class="form-control" required minlength="5" maxlength="1000" placeholder="Reason requirement was waived"><button class="btn btn-link text-danger">Waive uncollected requirement</button>{!! Form::close() !!}@endif</div></div>
@endif
<hr><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>Date</th><th>Type</th><th>Description / reference</th><th>Method</th><th>Amount</th><th>Status</th><th>Control</th></tr></thead><tbody>@forelse($securityDeposit->entries as $entry)<tr class="{{ $entry->status==='void'?'text-muted':'' }}"><td>{{ @format_date($entry->occurred_on) }}</td><td>{{ ucfirst(str_replace('_',' ',$entry->entry_type)) }}</td><td>{{ $entry->description }}<br><small>{{ $entry->reference }}</small>@if($entry->evidence_path)<br><a href="{{ Storage::disk('public')->url($entry->evidence_path) }}" target="_blank" rel="noopener">Evidence</a>@endif</td><td>{{ $paymentMethods[$entry->payment_method] ?? $entry->payment_method }}</td><td class="display_currency" data-currency_symbol="true">{{ $entry->amount }}</td><td>{{ ucfirst(str_replace('_',' ',$entry->status)) }}</td><td>@if($entry->entry_type==='refund' && $entry->status==='pending_approval' && (int)$entry->created_by !== (int)auth()->id() && (auth()->user()->can('property.deposit.refund') || auth()->user()->can('superadmin') || auth()->user()->hasRole('Admin#'.session('user.business_id')))){!! Form::open(['route'=>['property.deposits.refunds.approve',$entry]]) !!}<button class="btn btn-xs btn-success">Approve refund</button>{!! Form::close() !!}@elseif($entry->entry_type==='refund' && $entry->status==='pending_approval' && (int)$entry->created_by === (int)auth()->id())<small class="text-muted">Awaiting a different authorized approver</small>@endif @if($entry->entry_type==='refund' && $entry->status==='approved' && (auth()->user()->can('property.deposit.refund') || auth()->user()->can('superadmin') || auth()->user()->hasRole('Admin#'.session('user.business_id')))){!! Form::open(['route'=>['property.deposits.refunds.pay',$entry]]) !!}<button class="btn btn-xs btn-primary">Confirm refund paid</button>{!! Form::close() !!}@endif @if($entry->status!=='void' && (auth()->user()->can('property.deposit.refund') || auth()->user()->can('superadmin') || auth()->user()->hasRole('Admin#'.session('user.business_id'))))<button class="btn btn-xs btn-danger" data-toggle="collapse" data-target="#void-deposit-{{ $entry->id }}">Void</button>@endif</td></tr>@if($entry->status!=='void')<tr id="void-deposit-{{ $entry->id }}" class="collapse"><td colspan="7">{!! Form::open(['route'=>['property.deposits.entries.void',$entry],'class'=>'form-inline']) !!}<input name="reason" class="form-control" required minlength="3" maxlength="1000" placeholder="Audit reason"><button class="btn btn-danger">Confirm void</button>{!! Form::close() !!}</td></tr>@endif @empty<tr><td colspan="7" class="text-center text-muted">No security-deposit activity.</td></tr>@endforelse</tbody></table></div>
@php($linkedDamageDocuments = $securityDeposit->entries->whereNotNull('business_document_id'))
@if($linkedDamageDocuments->isNotEmpty())<p><strong>Linked damage invoices:</strong> @foreach($linkedDamageDocuments as $damageEntry)<a class="btn btn-xs btn-default" href="{{ route('smart-documents.show', $damageEntry->business_document_id) }}">Assessment #{{ $damageEntry->id }}</a> @endforeach</p>@endif
</div></div>
@endif
<div class="box box-info"><div class="box-header with-border"><h3 class="box-title">Payment Deposits (Advances)</h3></div><div class="box-body"><div class="row"><div class="col-md-5">@if(auth()->user()->can('property.rent.manage') || auth()->user()->can('superadmin') || auth()->user()->hasRole('Admin#'.session('user.business_id')))<h4>Receive advance</h4>{!! Form::open(['route'=>['property.deposits.payment',$model]]) !!}<div class="row"><div class="col-sm-6 form-group"><input type="number" name="amount" min="0.0001" step="0.0001" class="form-control" required placeholder="Amount"></div><div class="col-sm-6 form-group"><input type="date" name="received_on" value="{{ now()->toDateString() }}" class="form-control" required></div><div class="col-sm-6 form-group">{!! Form::select('payment_method',$paymentMethods,null,['class'=>'form-control','required','placeholder'=>'Payment method']) !!}</div><div class="col-sm-6 form-group">{!! Form::select('receipt_account_id',$accounts,null,['class'=>'form-control','placeholder'=>'Receipt account']) !!}</div><div class="col-sm-12 form-group"><input name="reference" class="form-control" maxlength="191" placeholder="Reference"></div><div class="col-sm-12"><button class="btn btn-info">Record Payment Deposit (Advance)</button></div></div>{!! Form::close() !!}@endif</div><div class="col-md-7"><div class="table-responsive"><table class="table table-condensed"><thead><tr><th>Date</th><th>Method/reference</th><th>Received</th><th>Applied to rent</th><th>Available</th><th>Status</th></tr></thead><tbody>@forelse($model->paymentDeposits as $advance)<tr><td>{{ @format_date($advance->received_on) }}</td><td>{{ $paymentMethods[$advance->payment_method] ?? $advance->payment_method }}<br><small>{{ $advance->reference }}</small></td><td class="display_currency" data-currency_symbol="true">{{ $advance->amount }}</td><td class="display_currency" data-currency_symbol="true">{{ $advance->applied_amount }}</td><td class="display_currency" data-currency_symbol="true">{{ $advance->available_amount }}</td><td>{{ ucfirst(str_replace('_',' ',$advance->status)) }}</td></tr>@empty<tr><td colspan="6" class="text-center text-muted">No rent advances recorded.</td></tr>@endforelse</tbody></table></div></div></div></div></div>
</section>
@endsection
