<?php

return [
    'profiles' => [
        'general_business' => [
            'audience' => 'For mixed trading, distribution, and other businesses that do not need a specialist operational workspace.',
            'workspace' => 'POS, sales, quotations, purchases, products, inventory, suppliers, customers, expenses, accounting, reports, and a separate Human Resource Management (HRM) workspace.',
            'questions' => [
                [
                    'key' => 'operating_model',
                    'type' => 'select',
                    'label' => 'What is your primary business model?',
                    'help' => 'This sets your starting navigation and setup checklist. You can enable other activities later.',
                    'required' => true,
                    'default' => 'retail_trading',
                    'options' => [
                        ['value' => 'retail_trading', 'label' => 'Retail trading'],
                        ['value' => 'wholesale_distribution', 'label' => 'Wholesale / distribution'],
                        ['value' => 'manufacturing', 'label' => 'Manufacturing / production'],
                        ['value' => 'import_export', 'label' => 'Import / export'],
                        ['value' => 'ecommerce', 'label' => 'E-commerce / online selling'],
                        ['value' => 'products_and_services', 'label' => 'Products and services'],
                        ['value' => 'mixed', 'label' => 'Mixed general business'],
                    ],
                ],
                [
                    'key' => 'business_activities',
                    'type' => 'multiselect',
                    'label' => 'Which activities does this company perform?',
                    'help' => 'Select all that apply so CashERP can prioritise the correct tools.',
                    'required' => true,
                    'min' => 1,
                    'default' => ['retail_sales'],
                    'options' => [
                        ['value' => 'retail_sales', 'label' => 'Retail / counter sales'],
                        ['value' => 'wholesale_sales', 'label' => 'Wholesale or account sales'],
                        ['value' => 'distribution', 'label' => 'Distribution and delivery'],
                        ['value' => 'manufacturing', 'label' => 'Manufacturing / assembly'],
                        ['value' => 'online_sales', 'label' => 'Online sales'],
                        ['value' => 'service_billing', 'label' => 'Service quotations and invoicing'],
                    ],
                ],
                ['key' => 'multiple_locations', 'type' => 'boolean', 'label' => 'Does this company operate from multiple locations?', 'help' => 'Locations remain separate for stock, sales, documents, staff permissions, and reports, within the package limit.', 'default' => false],
                ['key' => 'sells_products', 'label' => 'Do you sell physical products?', 'help' => 'We will prioritise products, stock, purchasing, and supplier setup.', 'default' => true],
                ['key' => 'sells_services', 'label' => 'Do you also sell services?', 'help' => 'Service items can be invoiced without stock quantities.', 'default' => false],
                ['key' => 'tracks_inventory', 'label' => 'Do you track stock quantities?', 'help' => 'Inventory alerts and stock movement tools remain available.', 'default' => true],
            ],
        ],
        'restaurant_food_service' => [
            'audience' => 'For dine-in, takeaway, delivery, cafes, bars, and catering.',
            'workspace' => 'POS, menus and products, tables, kitchen orders, dine-in, takeaway, delivery, split bills, food inventory, purchasing, accounting, reports, and a separate Human Resource Management (HRM) workspace.',
            'questions' => [
                [
                    'key' => 'operating_model', 'type' => 'select', 'required' => true,
                    'label' => 'What is your primary food-service model?',
                    'help' => 'This controls the recommended POS, menu, table, kitchen and fulfilment setup.',
                    'default' => 'full_service_restaurant',
                    'options' => [
                        ['value' => 'full_service_restaurant', 'label' => 'Full-service restaurant'],
                        ['value' => 'quick_service_fast_food', 'label' => 'Quick-service / fast food'],
                        ['value' => 'cafe_bakery', 'label' => 'Cafe / coffee shop / bakery'],
                        ['value' => 'bar_lounge', 'label' => 'Bar / pub / lounge'],
                        ['value' => 'catering_events', 'label' => 'Catering / events kitchen'],
                        ['value' => 'food_truck_kiosk', 'label' => 'Food truck / kiosk'],
                        ['value' => 'mixed', 'label' => 'Mixed food-service business'],
                    ],
                ],
                [
                    'key' => 'service_channels', 'type' => 'multiselect', 'required' => true, 'min' => 1,
                    'label' => 'How do customers receive orders?',
                    'help' => 'Select every active service channel.',
                    'default' => ['dine_in', 'takeaway'],
                    'options' => [
                        ['value' => 'dine_in', 'label' => 'Dine-in / table service'],
                        ['value' => 'counter_service', 'label' => 'Counter / quick service'],
                        ['value' => 'takeaway', 'label' => 'Takeaway / collection'],
                        ['value' => 'delivery', 'label' => 'Delivery'],
                        ['value' => 'catering', 'label' => 'Catering and events'],
                        ['value' => 'bar_service', 'label' => 'Bar service'],
                    ],
                ],
                ['key' => 'multiple_locations', 'type' => 'boolean', 'label' => 'Do you operate more than one outlet or location?', 'help' => 'Each outlet can have separate stock, registers, tables, staff permissions, documents, and reports.', 'default' => false],
                ['key' => 'kitchen_workflow', 'type' => 'boolean', 'label' => 'Do orders pass through a kitchen or preparation station?', 'help' => 'Kitchen order tickets and preparation status will be prioritised.', 'default' => true],
            ],
        ],
        'hotel_lodge_guesthouse' => [
            'audience' => 'For accommodation-first hotels, lodges, guest houses, and hostels.',
            'workspace' => 'Hotel Management System (HMS): rooms, guests, bookings, check-in and check-out, room prices, extras, coupons, housekeeping, accounting, assets, reports, and a separate Human Resource Management (HRM) workspace.',
            'questions' => [
                [
                    'key' => 'operating_model', 'type' => 'select', 'required' => true,
                    'label' => 'What type of accommodation business is this?',
                    'help' => 'Choose the primary model; additional accommodation types can be configured later.',
                    'default' => 'hotel',
                    'options' => [
                        ['value' => 'hotel', 'label' => 'Hotel'],
                        ['value' => 'lodge', 'label' => 'Lodge'],
                        ['value' => 'guest_house', 'label' => 'Guest house / bed and breakfast'],
                        ['value' => 'resort', 'label' => 'Resort'],
                        ['value' => 'hostel', 'label' => 'Hostel'],
                        ['value' => 'serviced_apartments', 'label' => 'Serviced apartments / extended stay'],
                        ['value' => 'motel', 'label' => 'Motel'],
                        ['value' => 'mixed', 'label' => 'Mixed accommodation portfolio'],
                    ],
                ],
                [
                    'key' => 'hospitality_services', 'type' => 'multiselect', 'required' => true, 'min' => 1,
                    'label' => 'Which hospitality services do you provide?',
                    'help' => 'These choices tailor bookings, folios, events, long-stay documents and guest-service setup.',
                    'default' => ['short_stay_accommodation'],
                    'options' => [
                        ['value' => 'short_stay_accommodation', 'label' => 'Short-stay accommodation'],
                        ['value' => 'long_stay_accommodation', 'label' => 'Long-stay / serviced accommodation'],
                        ['value' => 'conference_meetings', 'label' => 'Conference rooms / meetings'],
                        ['value' => 'weddings_events', 'label' => 'Weddings and social events'],
                        ['value' => 'airport_transfers', 'label' => 'Guest transfers / transport'],
                        ['value' => 'spa_recreation', 'label' => 'Spa / recreation / guest amenities'],
                        ['value' => 'breakfast_food_service', 'label' => 'Breakfast / cafe / food service'],
                        ['value' => 'room_service', 'label' => 'Room service'],
                    ],
                ],
                [
                    'key' => 'service_channels', 'type' => 'multiselect', 'required' => false,
                    'label' => 'Which food-service channels are used at this accommodation?',
                    'help' => 'Only select channels actually operated. Hotel Management and Restaurant Operations remain separate workspaces.',
                    'default' => [],
                    'options' => [
                        ['value' => 'dine_in', 'label' => 'Dining room / table service'],
                        ['value' => 'counter_service', 'label' => 'Cafe / counter service'],
                        ['value' => 'takeaway', 'label' => 'Takeaway / collection'],
                        ['value' => 'room_service', 'label' => 'Room service'],
                        ['value' => 'catering', 'label' => 'Events / banqueting'],
                    ],
                ],
                ['key' => 'multiple_locations', 'type' => 'boolean', 'label' => 'Do you operate multiple hotels, lodges, or locations?', 'help' => 'Properties, rooms, bookings, staff access, folios, and reports remain location-specific.', 'default' => false],
                ['key' => 'online_bookings', 'label' => 'Do you accept advance or online bookings?', 'help' => 'We will prioritise booking, guest, rate, and availability setup.', 'default' => true],
                ['key' => 'daily_housekeeping', 'label' => 'Do you provide daily housekeeping?', 'help' => 'Housekeeping assignments and room-readiness checks will be highlighted.', 'default' => true],
                ['key' => 'extra_services', 'label' => 'Do you charge for extras or guest services?', 'help' => 'Extras and service pricing will be included in your setup guidance.', 'default' => true],
                ['key' => 'kitchen_workflow', 'type' => 'boolean', 'label' => 'Do food orders pass through a kitchen or preparation station?', 'help' => 'Enable this only when the accommodation operates food service.', 'default' => false],
            ],
        ],
        'hotel_with_restaurant' => [
            'audience' => 'For accommodation businesses with food, bar, or room service.',
            'workspace' => 'All HMS accommodation features plus restaurant POS, tables, kitchen orders, food inventory, bar and room service, purchasing, combined reporting, and a separate Human Resource Management (HRM) workspace.',
            'questions' => [
                [
                    'key' => 'operating_model', 'type' => 'select', 'required' => true,
                    'label' => 'What is your primary accommodation model?',
                    'help' => 'The hotel and restaurant remain distinct operational areas within the same company.',
                    'default' => 'hotel_restaurant',
                    'options' => [
                        ['value' => 'hotel_restaurant', 'label' => 'Hotel with restaurant'],
                        ['value' => 'lodge_restaurant', 'label' => 'Lodge with restaurant / bar'],
                        ['value' => 'guest_house_restaurant', 'label' => 'Guest house with food service'],
                        ['value' => 'resort_food_beverage', 'label' => 'Resort with food and beverage outlets'],
                        ['value' => 'multi_property_hospitality', 'label' => 'Multi-property hospitality group'],
                    ],
                ],
                [
                    'key' => 'service_channels', 'type' => 'multiselect', 'required' => true, 'min' => 1,
                    'label' => 'Which food and beverage channels do you operate?',
                    'help' => 'Select all channels used alongside accommodation.',
                    'default' => ['dine_in', 'room_service'],
                    'options' => [
                        ['value' => 'dine_in', 'label' => 'Restaurant dine-in / table service'],
                        ['value' => 'room_service', 'label' => 'Room service'],
                        ['value' => 'counter_service', 'label' => 'Counter / quick service'],
                        ['value' => 'takeaway', 'label' => 'Takeaway / collection'],
                        ['value' => 'delivery', 'label' => 'Delivery'],
                        ['value' => 'bar_service', 'label' => 'Bar / lounge service'],
                        ['value' => 'catering', 'label' => 'Catering / banqueting'],
                    ],
                ],
                ['key' => 'multiple_locations', 'type' => 'boolean', 'label' => 'Do you operate multiple hospitality locations?', 'help' => 'Rooms, restaurant outlets, stock, staff permissions, transactions, and reports remain location-specific.', 'default' => false],
                ['key' => 'kitchen_workflow', 'type' => 'boolean', 'label' => 'Do food orders pass through a kitchen or preparation station?', 'help' => 'Kitchen order tickets and preparation status will be prioritised.', 'default' => true],
            ],
        ],
        'property_management_rentals' => [
            'audience' => 'For property owners, landlords, real estate agencies, developers, facilities teams, estate managers, and third-party property managers.',
            'workspace' => 'Multi-location real estate portfolios, properties, units, tenants, leases, rent schedules, deposits, maintenance, owner and tenant ledgers, accounting, CRM, reports, and a separate Human Resource Management (HRM) workspace.',
            'questions' => [
                [
                    'key' => 'operating_model',
                    'type' => 'select',
                    'label' => 'What is your primary real estate business model?',
                    'help' => 'This sets your starting dashboard and terminology. It does not prevent you from adding other property activities later.',
                    'required' => true,
                    'default' => 'owner_landlord',
                    'options' => [
                        ['value' => 'owner_landlord', 'label' => 'Property owner / landlord'],
                        ['value' => 'third_party_manager', 'label' => 'Third-party property management company'],
                        ['value' => 'real_estate_agency', 'label' => 'Real estate agency / brokerage'],
                        ['value' => 'property_developer', 'label' => 'Property developer'],
                        ['value' => 'facilities_estate_manager', 'label' => 'Facilities / estate management company'],
                        ['value' => 'hybrid', 'label' => 'Hybrid real estate business'],
                    ],
                ],
                [
                    'key' => 'portfolio_category',
                    'type' => 'select',
                    'label' => 'What is your primary portfolio category?',
                    'help' => 'Choose the closest primary category. A mixed portfolio may contain property types from several categories.',
                    'required' => true,
                    'default' => 'residential',
                    'options' => [
                        ['value' => 'residential', 'label' => 'Residential property'],
                        ['value' => 'commercial', 'label' => 'Commercial property'],
                        ['value' => 'mixed_use', 'label' => 'Mixed-use property'],
                        ['value' => 'industrial_logistics', 'label' => 'Industrial and logistics property'],
                        ['value' => 'land', 'label' => 'Land and plots'],
                        ['value' => 'community_association', 'label' => 'Estate, community, strata or association management'],
                        ['value' => 'mixed_portfolio', 'label' => 'Mixed property portfolio'],
                    ],
                ],
                [
                    'key' => 'property_subtypes',
                    'type' => 'multiselect',
                    'label' => 'Which property types do you manage?',
                    'help' => 'Select every type that applies. For example, Commercial can include a shopping mall, office park, retail centre, warehouse, or several of these.',
                    'required' => true,
                    'min' => 1,
                    'default' => ['apartments'],
                    'depends_on' => 'portfolio_category',
                    'show_all_for' => ['mixed_portfolio'],
                    'options' => [
                        ['value' => 'apartments', 'label' => 'Residential - apartments / flats', 'parent' => 'residential'],
                        ['value' => 'single_family', 'label' => 'Residential - houses / single-family homes', 'parent' => 'residential'],
                        ['value' => 'gated_estate', 'label' => 'Residential - gated estate / housing complex', 'parent' => 'residential'],
                        ['value' => 'student_housing', 'label' => 'Residential - student housing / hostels', 'parent' => 'residential'],
                        ['value' => 'serviced_residences', 'label' => 'Residential - serviced residences', 'parent' => 'residential'],
                        ['value' => 'shopping_mall', 'label' => 'Commercial - shopping mall / retail centre', 'parent' => 'commercial'],
                        ['value' => 'office_building', 'label' => 'Commercial - office building / office park', 'parent' => 'commercial'],
                        ['value' => 'street_retail', 'label' => 'Commercial - shops / street retail', 'parent' => 'commercial'],
                        ['value' => 'business_centre', 'label' => 'Commercial - business centre / co-working property', 'parent' => 'commercial'],
                        ['value' => 'medical_offices', 'label' => 'Commercial - medical / professional offices', 'parent' => 'commercial'],
                        ['value' => 'mixed_use_development', 'label' => 'Mixed-use - residential and commercial development', 'parent' => 'mixed_use'],
                        ['value' => 'warehouse', 'label' => 'Industrial - warehouse / distribution centre', 'parent' => 'industrial_logistics'],
                        ['value' => 'industrial_park', 'label' => 'Industrial - factory / industrial park', 'parent' => 'industrial_logistics'],
                        ['value' => 'logistics_hub', 'label' => 'Industrial - logistics hub', 'parent' => 'industrial_logistics'],
                        ['value' => 'plots', 'label' => 'Land - serviced plots / subdivisions', 'parent' => 'land'],
                        ['value' => 'development_land', 'label' => 'Land - development or investment land', 'parent' => 'land'],
                        ['value' => 'agricultural_land', 'label' => 'Land - agricultural property', 'parent' => 'land'],
                        ['value' => 'estate_association', 'label' => 'Community - estate / homeowners association', 'parent' => 'community_association'],
                        ['value' => 'strata_condominium', 'label' => 'Community - strata / condominium management', 'parent' => 'community_association'],
                        ['value' => 'other', 'label' => 'Other real estate property type', 'parent' => 'mixed_portfolio'],
                    ],
                ],
                ['key' => 'multiple_locations', 'type' => 'boolean', 'label' => 'Do you operate from or report across multiple locations?', 'help' => 'CashERP will guide you to add locations within your package limit and assign each property to the correct location.', 'default' => false],
                ['key' => 'third_party_owners', 'type' => 'boolean', 'label' => 'Do you manage properties for other owners?', 'help' => 'Owner statements, management reporting, and owner-specific portfolio tracking will be prioritised.', 'default' => false],
                ['key' => 'maintenance_tracking', 'type' => 'boolean', 'label' => 'Do you manage maintenance requests?', 'help' => 'Maintenance tickets, assignments, costs, and completion records will be highlighted.', 'default' => true],
            ],
        ],
        'professional_services' => [
            'audience' => 'For consultancies, agencies, studios, and client or project-led firms.',
            'workspace' => 'CRM, proposals, projects, tasks, documents, invoices, expenses, and accounting. Human Resource Management (HRM) is available as a separate staff workspace.',
            'questions' => [
                [
                    'key' => 'operating_model', 'type' => 'select', 'required' => true,
                    'label' => 'What is your primary professional-service model?',
                    'help' => 'This configures the recommended client, project, billing, document, and reporting workflow.',
                    'default' => 'consulting',
                    'options' => [
                        ['value' => 'consulting', 'label' => 'Consulting / advisory'],
                        ['value' => 'agency', 'label' => 'Agency / outsourced services'],
                        ['value' => 'accounting', 'label' => 'Accounting / bookkeeping'],
                        ['value' => 'legal_compliance', 'label' => 'Legal / compliance services'],
                        ['value' => 'engineering_architecture', 'label' => 'Engineering / architecture'],
                        ['value' => 'it_technology', 'label' => 'IT / technology services'],
                        ['value' => 'creative_studio', 'label' => 'Creative / design studio'],
                        ['value' => 'field_services', 'label' => 'Field / maintenance services'],
                        ['value' => 'mixed', 'label' => 'Mixed professional services'],
                    ],
                ],
                [
                    'key' => 'billing_models', 'type' => 'multiselect', 'required' => true, 'min' => 1,
                    'label' => 'How do you charge clients?',
                    'help' => 'Select all billing methods used by the company.',
                    'default' => ['fixed_fee'],
                    'options' => [
                        ['value' => 'fixed_fee', 'label' => 'Fixed fee'],
                        ['value' => 'hourly_time', 'label' => 'Hourly / time-based'],
                        ['value' => 'retainer', 'label' => 'Retainer'],
                        ['value' => 'milestone_progress', 'label' => 'Milestone / progress billing'],
                        ['value' => 'recurring_subscription', 'label' => 'Recurring / subscription billing'],
                        ['value' => 'commission', 'label' => 'Commission / success fee'],
                    ],
                ],
                ['key' => 'multiple_locations', 'type' => 'boolean', 'label' => 'Does the firm operate from multiple offices or locations?', 'help' => 'Projects, staff permissions, expenses, invoices, and reports can remain location-specific.', 'default' => false],
                ['key' => 'project_based_work', 'label' => 'Do you organise work by project?', 'help' => 'Projects, tasks, milestones, and client collaboration will be prioritised.', 'default' => true],
                ['key' => 'time_tracking', 'label' => 'Do you bill or report by time?', 'help' => 'Time and activity tracking will be included in your setup guidance.', 'default' => false],
                ['key' => 'recurring_invoices', 'label' => 'Do you send recurring invoices?', 'help' => 'Recurring client billing requirements will be recorded for setup.', 'default' => false],
            ],
        ],
        'retail_wholesale' => [
            'audience' => 'For retailers, wholesalers, distributors, supermarkets, and multi-branch stores.',
            'workspace' => 'POS, quotations, sales orders, invoices, receipts, delivery and return notes, purchasing, inventory, accounting, reports, and a separate Human Resource Management (HRM) workspace.',
            'questions' => [
                ['key' => 'retail_counter', 'label' => 'Do you sell through a retail counter?', 'help' => 'POS and receipt workflows will be prioritised.', 'default' => true],
                ['key' => 'wholesale_orders', 'label' => 'Do you fulfil wholesale or account orders?', 'help' => 'Sales orders, quotations, delivery notes, and customer credit workflows will be highlighted.', 'default' => false],
                ['key' => 'tracks_inventory', 'label' => 'Do you track stock quantities?', 'help' => 'Inventory, purchasing, and reorder tools will remain available.', 'default' => true],
            ],
        ],
        'construction_contracting' => [
            'audience' => 'For builders, contractors, engineers, quantity surveyors, and project delivery firms.',
            'workspace' => 'Projects, estimates, work orders, progress claims, procurement, suppliers, inventory, expenses, accounting, assets, reports, and separate HRM.',
            'questions' => [
                ['key' => 'progress_billing', 'label' => 'Do you bill by project progress?', 'help' => 'Progress claims and retention fields will be prioritised.', 'default' => true],
                ['key' => 'uses_subcontractors', 'label' => 'Do you use subcontractors?', 'help' => 'Supplier and procurement workflows will be highlighted.', 'default' => true],
                ['key' => 'tracks_materials', 'label' => 'Do you track site materials?', 'help' => 'Inventory and purchasing tools will be included.', 'default' => true],
            ],
        ],
        'healthcare_clinic' => [
            'audience' => 'For clinics, medical centres, dental practices, laboratories, and wellness providers.',
            'workspace' => 'Patient-facing estimates, invoices, receipts and insurer summaries, CRM, expenses, accounting, assets, reports, and separate HRM. Clinical records remain outside commercial documents.',
            'questions' => [
                ['key' => 'insurance_billing', 'label' => 'Do you bill insurers?', 'help' => 'Insurance references and claim-summary documents will be available.', 'default' => false],
                ['key' => 'appointment_services', 'label' => 'Do you sell scheduled services?', 'help' => 'Service dates and provider fields will be prioritised.', 'default' => true],
            ],
        ],
        'education_training' => [
            'audience' => 'For schools, colleges, academies, tutors, and professional training providers.',
            'workspace' => 'Enrollment confirmations, tuition invoices, fee receipts, CRM, projects, expenses, accounting, reports, and separate HRM.',
            'questions' => [
                ['key' => 'term_billing', 'label' => 'Do you bill by term or academic period?', 'help' => 'Academic-period billing references will be prioritised.', 'default' => true],
                ['key' => 'guardian_billing', 'label' => 'Do parents or guardians pay fees?', 'help' => 'Student and payer details will be kept distinct.', 'default' => true],
            ],
        ],
        'automotive_services' => [
            'audience' => 'For workshops, garages, parts and service centres, and vehicle repair businesses.',
            'workspace' => 'Vehicle estimates, repair authorizations, service invoices, receipts, POS, parts inventory, purchasing, CRM, accounting, assets, reports, and separate HRM.',
            'questions' => [
                ['key' => 'repair_workshop', 'label' => 'Do you perform vehicle repairs or servicing?', 'help' => 'Inspection, authorization, and work-order fields will be prioritised.', 'default' => true],
                ['key' => 'sells_parts', 'label' => 'Do you sell spare parts?', 'help' => 'POS, products, inventory, and purchasing will be highlighted.', 'default' => true],
            ],
        ],
        'logistics_transport' => [
            'audience' => 'For freight, courier, delivery, haulage, fleet, and transport service providers.',
            'workspace' => 'Freight quotations, consignment notes, invoices, proof of delivery, CRM, purchasing, inventory, expenses, accounting, assets, reports, and separate HRM.',
            'questions' => [
                ['key' => 'proof_of_delivery', 'label' => 'Do you require proof of delivery?', 'help' => 'Receiver authorization and delivery confirmation will be prioritised.', 'default' => true],
                ['key' => 'cross_border', 'label' => 'Do you handle cross-border shipments?', 'help' => 'Origin, destination, carrier, and tracking references will be highlighted.', 'default' => false],
            ],
        ],
        'nonprofit_membership' => [
            'audience' => 'For charities, associations, clubs, foundations, and membership organisations.',
            'workspace' => 'Donation acknowledgements and receipts, membership invoices and receipts, CRM, projects, expenses, accounting, assets, reports, and separate HRM.',
            'questions' => [
                ['key' => 'accepts_donations', 'label' => 'Do you accept donations?', 'help' => 'Donor, campaign, restriction, and receipt fields will be available.', 'default' => true],
                ['key' => 'charges_membership', 'label' => 'Do you charge membership subscriptions?', 'help' => 'Membership billing documents will be prioritised.', 'default' => false],
            ],
        ],
    ],
];
