<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Smart document scenarios
    |--------------------------------------------------------------------------
    |
    | Scenarios describe the commercial event. The resolver combines the
    | scenario with the active company's industry and available source record
    | to recommend the correct output. An explicit type may still be selected
    | from the company's approved industry profile.
    |
    */
    'scenarios' => [
        'sale' => ['name' => 'General sale', 'help' => 'Quote, invoice, receipt or credit note for ordinary goods and services.'],
        'rental' => ['name' => 'Property rental', 'help' => 'Rental quotation, lease agreement, recurring rent invoice or rent receipt.'],
        'security_deposit' => ['name' => 'Refundable security deposit', 'help' => 'Request, receive, assess damage against, settle or refund money held for risk. It is not revenue and never reduces an invoice.'],
        'short_stay' => ['name' => 'Hotel short stay', 'help' => 'Room quotation, booking invoice, guest folio or booking payment receipt.'],
        'long_stay' => ['name' => 'Hotel long stay', 'help' => 'Accommodation agreement plus recurring or final billing outputs.'],
        'event' => ['name' => 'Event or venue booking', 'help' => 'Event quotation, reservation contract and event invoice.'],
        'catering' => ['name' => 'Catering service', 'help' => 'Catering quotation and invoice kept separate from accommodation charges.'],
        'professional_service' => ['name' => 'Professional service', 'help' => 'Proposal, service contract, milestone or final invoice.'],
        'retail_order' => ['name' => 'Retail or wholesale order', 'help' => 'Customer order, delivery, invoice, POS receipt or goods return.'],
        'construction_project' => ['name' => 'Construction project', 'help' => 'Estimate, work order, progress claim, completion record and final invoice.'],
        'healthcare_service' => ['name' => 'Healthcare billing', 'help' => 'Patient estimate, invoice, receipt or non-clinical insurance claim summary.'],
        'education_fee' => ['name' => 'Education fee', 'help' => 'Enrollment confirmation, tuition invoice and school-fee receipt.'],
        'automotive_service' => ['name' => 'Vehicle service', 'help' => 'Inspection estimate, repair authorization, job invoice and receipt.'],
        'logistics_shipment' => ['name' => 'Freight or delivery', 'help' => 'Freight quotation, consignment note, invoice and proof of delivery.'],
        'donation_membership' => ['name' => 'Donation or membership', 'help' => 'Donation acknowledgement, donation receipt and membership billing.'],
        'payment' => ['name' => 'Payment received', 'help' => 'Receipt tied to the relevant invoice, rent, booking, deposit or service.'],
    ],

    'long_stay_nights' => 28,

    'types' => [
        'standard_quotation' => [
            'name' => 'Standard Quotation', 'title' => 'Quotation', 'category' => 'commercial',
            'prefix' => 'QUO', 'scenario' => 'sale', 'schema' => 'commercial', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => false, 'convert_to' => 'standard_invoice',
        ],
        'proforma_invoice' => [
            'name' => 'Proforma Invoice', 'title' => 'Proforma Invoice', 'category' => 'commercial',
            'prefix' => 'PRO', 'scenario' => 'sale', 'schema' => 'commercial', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => false, 'convert_to' => 'standard_invoice',
        ],
        'standard_invoice' => [
            'name' => 'Standard Invoice', 'title' => 'Sales Invoice', 'category' => 'financial',
            'prefix' => 'INV', 'scenario' => 'sale', 'schema' => 'commercial', 'supports_lines' => true,
            'is_financial' => true, 'requires_acceptance' => false,
        ],
        'payment_receipt' => [
            'name' => 'Payment Receipt', 'title' => 'Payment Receipt', 'category' => 'financial',
            'prefix' => 'RCP', 'scenario' => 'payment', 'schema' => 'payment', 'supports_lines' => true,
            'is_financial' => true, 'requires_acceptance' => false,
        ],
        'credit_note' => [
            'name' => 'Credit Note', 'title' => 'Credit Note', 'category' => 'financial',
            'prefix' => 'CRN', 'scenario' => 'sale', 'schema' => 'commercial', 'supports_lines' => true,
            'is_financial' => true, 'requires_acceptance' => false,
        ],
        'delivery_note' => [
            'name' => 'Delivery Note', 'title' => 'Delivery Note', 'category' => 'operational',
            'prefix' => 'DLV', 'scenario' => 'sale', 'schema' => 'commercial', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => false,
        ],
        'pos_receipt' => [
            'name' => 'POS Receipt', 'title' => 'Sales Receipt', 'category' => 'financial',
            'prefix' => 'POS-R', 'scenario' => 'payment', 'schema' => 'payment', 'supports_lines' => true,
            'output_format' => 'receipt_80mm', 'is_financial' => true, 'requires_acceptance' => false,
        ],
        'sales_order' => [
            'name' => 'Sales Order', 'title' => 'Sales Order', 'category' => 'operational',
            'prefix' => 'SO', 'scenario' => 'retail_order', 'schema' => 'commercial', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => false, 'convert_to' => 'standard_invoice',
        ],
        'goods_return_note' => [
            'name' => 'Goods Return Note', 'title' => 'Goods Return Note', 'category' => 'operational',
            'prefix' => 'GRN', 'scenario' => 'retail_order', 'schema' => 'commercial', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => false, 'convert_to' => 'credit_note',
        ],
        'catering_quotation' => [
            'name' => 'Catering Quotation', 'title' => 'Catering Quotation', 'category' => 'commercial',
            'prefix' => 'CAT-Q', 'scenario' => 'catering', 'schema' => 'event', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => false, 'convert_to' => 'catering_invoice',
        ],
        'catering_invoice' => [
            'name' => 'Catering Invoice', 'title' => 'Catering Invoice', 'category' => 'financial',
            'prefix' => 'CAT-I', 'scenario' => 'catering', 'schema' => 'event', 'supports_lines' => true,
            'is_financial' => true, 'requires_acceptance' => false,
        ],
        'room_booking_quotation' => [
            'name' => 'Accommodation Quotation', 'title' => 'Accommodation Quotation', 'category' => 'commercial',
            'prefix' => 'STAY-Q', 'scenario' => 'short_stay', 'schema' => 'stay', 'supports_lines' => true,
            'output_format' => 'a4', 'is_financial' => false, 'requires_acceptance' => false, 'convert_to' => 'room_booking_invoice',
        ],
        'room_booking_invoice' => [
            'name' => 'Accommodation Invoice', 'title' => 'Accommodation Invoice', 'category' => 'financial',
            'prefix' => 'STAY-I', 'scenario' => 'short_stay', 'schema' => 'stay', 'supports_lines' => true,
            'output_format' => 'a4', 'is_financial' => true, 'requires_acceptance' => false,
        ],
        'booking_payment_receipt' => [
            'name' => 'Accommodation Payment Receipt', 'title' => 'Accommodation Payment Receipt', 'category' => 'financial',
            'prefix' => 'STAY-R', 'scenario' => 'payment', 'schema' => 'stay_payment', 'supports_lines' => true,
            'output_format' => 'a4', 'is_financial' => true, 'requires_acceptance' => false,
        ],
        'guest_folio' => [
            'name' => 'Guest Folio', 'title' => 'Guest Folio', 'category' => 'financial',
            'prefix' => 'FOL', 'scenario' => 'short_stay', 'schema' => 'stay', 'supports_lines' => true,
            'is_financial' => true, 'requires_acceptance' => false,
        ],
        'long_stay_agreement' => [
            'name' => 'Long-Stay Accommodation Agreement', 'title' => 'Long-Stay Accommodation Agreement', 'category' => 'agreement',
            'prefix' => 'LSA', 'scenario' => 'long_stay', 'schema' => 'lease', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => true, 'convert_to' => 'room_booking_invoice',
        ],
        'event_quotation' => [
            'name' => 'Event / Venue Quotation', 'title' => 'Event / Venue Quotation', 'category' => 'commercial',
            'prefix' => 'EVQ', 'scenario' => 'event', 'schema' => 'event', 'supports_lines' => true,
            'output_format' => 'a4', 'is_financial' => false, 'requires_acceptance' => false, 'convert_to' => 'event_reservation_contract',
        ],
        'event_reservation_contract' => [
            'name' => 'Event Reservation Contract', 'title' => 'Event Booking Contract & Reservation Form', 'category' => 'agreement',
            'prefix' => 'EVC', 'scenario' => 'event', 'schema' => 'event', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => true, 'convert_to' => 'event_booking_invoice',
        ],
        'event_booking_invoice' => [
            'name' => 'Event / Venue Sales Invoice', 'title' => 'Event / Venue Sales Invoice', 'category' => 'financial',
            'prefix' => 'EVI', 'scenario' => 'event', 'schema' => 'event', 'supports_lines' => true,
            'output_format' => 'a4', 'is_financial' => true, 'requires_acceptance' => false,
        ],
        'event_payment_receipt' => [
            'name' => 'Event / Venue Payment Receipt', 'title' => 'Event / Venue Payment Receipt', 'category' => 'financial',
            'prefix' => 'EVR', 'scenario' => 'payment', 'schema' => 'event_payment', 'supports_lines' => true,
            'output_format' => 'a4', 'is_financial' => true, 'requires_acceptance' => false,
        ],
        'rental_quotation' => [
            'name' => 'Rental Quotation', 'title' => 'Rental Quotation', 'category' => 'commercial',
            'prefix' => 'RENT-Q', 'scenario' => 'rental', 'schema' => 'lease', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => false, 'convert_to' => 'lease_agreement',
        ],
        'lease_agreement' => [
            'name' => 'Lease Agreement', 'title' => 'Lease Agreement', 'category' => 'agreement',
            'prefix' => 'LEA', 'scenario' => 'rental', 'schema' => 'lease', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => true, 'convert_to' => 'rental_invoice',
        ],
        'rental_invoice' => [
            'name' => 'Rental Invoice', 'title' => 'Rental Invoice', 'category' => 'financial',
            'prefix' => 'RENT-I', 'scenario' => 'rental', 'schema' => 'lease', 'supports_lines' => true,
            'is_financial' => true, 'requires_acceptance' => false,
        ],
        'rent_receipt' => [
            'name' => 'Rent Receipt', 'title' => 'Rent Payment Receipt', 'category' => 'financial',
            'prefix' => 'RENT-R', 'scenario' => 'payment', 'schema' => 'rental_payment', 'supports_lines' => true,
            'is_financial' => true, 'requires_acceptance' => false,
        ],
        'security_deposit_receipt' => [
            'name' => 'Security Deposit Receipt', 'title' => 'Refundable Security Deposit Receipt', 'category' => 'liability',
            'prefix' => 'DEP-R', 'scenario' => 'security_deposit', 'schema' => 'rental_payment', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => false,
        ],
        'security_deposit_request' => [
            'name' => 'Security Deposit Request', 'title' => 'Refundable Security Deposit Request', 'category' => 'liability',
            'prefix' => 'DEP-Q', 'scenario' => 'security_deposit', 'schema' => 'rental_payment', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => false,
        ],
        'damage_assessment' => [
            'name' => 'Damage Assessment', 'title' => 'Damage Assessment & Deposit Deduction', 'category' => 'operational',
            'prefix' => 'DMG', 'scenario' => 'security_deposit', 'schema' => 'damage_assessment', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => true,
        ],
        'damage_charge_invoice' => [
            'name' => 'Damage Charge Invoice', 'title' => 'Damage or Loss Charge Invoice', 'category' => 'financial',
            'prefix' => 'DMG-I', 'scenario' => 'security_deposit', 'schema' => 'damage_assessment', 'supports_lines' => true,
            'is_financial' => true, 'requires_acceptance' => false,
        ],
        'security_deposit_settlement' => [
            'name' => 'Security Deposit Settlement', 'title' => 'Refundable Security Deposit Settlement Statement', 'category' => 'liability',
            'prefix' => 'DEP-S', 'scenario' => 'security_deposit', 'schema' => 'deposit_settlement', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => false,
        ],
        'owner_statement' => [
            'name' => 'Property Owner Statement', 'title' => 'Property Owner Statement', 'category' => 'financial',
            'prefix' => 'OWN-S', 'scenario' => 'rental', 'schema' => 'lease', 'supports_lines' => true,
            'is_financial' => true, 'requires_acceptance' => false,
        ],
        'service_proposal' => [
            'name' => 'Service Proposal', 'title' => 'Professional Service Proposal', 'category' => 'commercial',
            'prefix' => 'PRO-P', 'scenario' => 'professional_service', 'schema' => 'professional', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => false, 'convert_to' => 'service_contract',
        ],
        'service_contract' => [
            'name' => 'Service Contract', 'title' => 'Professional Service Agreement', 'category' => 'agreement',
            'prefix' => 'PRO-C', 'scenario' => 'professional_service', 'schema' => 'professional', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => true, 'convert_to' => 'service_invoice',
        ],
        'service_invoice' => [
            'name' => 'Service Invoice', 'title' => 'Professional Service Invoice', 'category' => 'financial',
            'prefix' => 'PRO-I', 'scenario' => 'professional_service', 'schema' => 'professional', 'supports_lines' => true,
            'is_financial' => true, 'requires_acceptance' => false,
        ],
        'retainer_receipt' => [
            'name' => 'Retainer Receipt', 'title' => 'Retainer Payment Receipt', 'category' => 'financial',
            'prefix' => 'RET-R', 'scenario' => 'payment', 'schema' => 'professional_payment', 'supports_lines' => true,
            'is_financial' => true, 'requires_acceptance' => false,
        ],
        'construction_estimate' => [
            'name' => 'Construction Estimate', 'title' => 'Project Estimate', 'category' => 'commercial',
            'prefix' => 'EST', 'scenario' => 'construction_project', 'schema' => 'construction', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => false, 'convert_to' => 'construction_work_order',
        ],
        'construction_work_order' => [
            'name' => 'Construction Work Order', 'title' => 'Work Order', 'category' => 'agreement',
            'prefix' => 'WO', 'scenario' => 'construction_project', 'schema' => 'construction', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => true, 'convert_to' => 'progress_invoice',
        ],
        'progress_invoice' => [
            'name' => 'Progress Invoice', 'title' => 'Progress Claim / Invoice', 'category' => 'financial',
            'prefix' => 'PRG-I', 'scenario' => 'construction_project', 'schema' => 'construction', 'supports_lines' => true,
            'is_financial' => true, 'requires_acceptance' => false,
        ],
        'completion_certificate' => [
            'name' => 'Completion Certificate', 'title' => 'Works Completion Certificate', 'category' => 'operational',
            'prefix' => 'CMP', 'scenario' => 'construction_project', 'schema' => 'construction', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => true,
        ],
        'patient_estimate' => [
            'name' => 'Patient Cost Estimate', 'title' => 'Patient Cost Estimate', 'category' => 'commercial',
            'prefix' => 'PAT-Q', 'scenario' => 'healthcare_service', 'schema' => 'healthcare_billing', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => false, 'convert_to' => 'patient_invoice',
        ],
        'patient_invoice' => [
            'name' => 'Patient Invoice', 'title' => 'Patient Invoice', 'category' => 'financial',
            'prefix' => 'PAT-I', 'scenario' => 'healthcare_service', 'schema' => 'healthcare_billing', 'supports_lines' => true,
            'is_financial' => true, 'requires_acceptance' => false,
        ],
        'medical_payment_receipt' => [
            'name' => 'Medical Payment Receipt', 'title' => 'Patient Payment Receipt', 'category' => 'financial',
            'prefix' => 'PAT-R', 'scenario' => 'payment', 'schema' => 'healthcare_payment', 'supports_lines' => true,
            'is_financial' => true, 'requires_acceptance' => false,
        ],
        'insurance_claim_summary' => [
            'name' => 'Insurance Claim Summary', 'title' => 'Insurance Claim Summary', 'category' => 'operational',
            'prefix' => 'CLM', 'scenario' => 'healthcare_service', 'schema' => 'healthcare_billing', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => false,
        ],
        'tuition_invoice' => [
            'name' => 'Tuition Invoice', 'title' => 'Tuition and School Fees Invoice', 'category' => 'financial',
            'prefix' => 'TUI-I', 'scenario' => 'education_fee', 'schema' => 'education_billing', 'supports_lines' => true,
            'is_financial' => true, 'requires_acceptance' => false,
        ],
        'fee_receipt' => [
            'name' => 'School Fee Receipt', 'title' => 'Tuition and School Fees Receipt', 'category' => 'financial',
            'prefix' => 'TUI-R', 'scenario' => 'payment', 'schema' => 'education_payment', 'supports_lines' => true,
            'is_financial' => true, 'requires_acceptance' => false,
        ],
        'enrollment_confirmation' => [
            'name' => 'Enrollment Confirmation', 'title' => 'Enrollment Confirmation', 'category' => 'operational',
            'prefix' => 'ENR', 'scenario' => 'education_fee', 'schema' => 'education_billing', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => false,
        ],
        'vehicle_service_estimate' => [
            'name' => 'Vehicle Service Estimate', 'title' => 'Inspection and Service Estimate', 'category' => 'commercial',
            'prefix' => 'VEH-Q', 'scenario' => 'automotive_service', 'schema' => 'automotive', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => false, 'convert_to' => 'repair_work_order',
        ],
        'repair_work_order' => [
            'name' => 'Repair Work Order', 'title' => 'Vehicle Repair Authorization', 'category' => 'agreement',
            'prefix' => 'VEH-WO', 'scenario' => 'automotive_service', 'schema' => 'automotive', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => true, 'convert_to' => 'vehicle_service_invoice',
        ],
        'vehicle_service_invoice' => [
            'name' => 'Vehicle Service Invoice', 'title' => 'Vehicle Service Invoice', 'category' => 'financial',
            'prefix' => 'VEH-I', 'scenario' => 'automotive_service', 'schema' => 'automotive', 'supports_lines' => true,
            'is_financial' => true, 'requires_acceptance' => false,
        ],
        'freight_quotation' => [
            'name' => 'Freight Quotation', 'title' => 'Freight Quotation', 'category' => 'commercial',
            'prefix' => 'FRT-Q', 'scenario' => 'logistics_shipment', 'schema' => 'logistics', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => false, 'convert_to' => 'consignment_note',
        ],
        'consignment_note' => [
            'name' => 'Consignment Note', 'title' => 'Consignment / Waybill', 'category' => 'operational',
            'prefix' => 'CN', 'scenario' => 'logistics_shipment', 'schema' => 'logistics', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => false, 'convert_to' => 'freight_invoice',
        ],
        'freight_invoice' => [
            'name' => 'Freight Invoice', 'title' => 'Freight and Delivery Invoice', 'category' => 'financial',
            'prefix' => 'FRT-I', 'scenario' => 'logistics_shipment', 'schema' => 'logistics', 'supports_lines' => true,
            'is_financial' => true, 'requires_acceptance' => false,
        ],
        'proof_of_delivery' => [
            'name' => 'Proof of Delivery', 'title' => 'Proof of Delivery', 'category' => 'operational',
            'prefix' => 'POD', 'scenario' => 'logistics_shipment', 'schema' => 'logistics', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => true,
        ],
        'donation_acknowledgement' => [
            'name' => 'Donation Acknowledgement', 'title' => 'Donation Acknowledgement', 'category' => 'operational',
            'prefix' => 'DON-A', 'scenario' => 'donation_membership', 'schema' => 'nonprofit', 'supports_lines' => true,
            'is_financial' => false, 'requires_acceptance' => false,
        ],
        'donation_receipt' => [
            'name' => 'Donation Receipt', 'title' => 'Donation Receipt', 'category' => 'financial',
            'prefix' => 'DON-R', 'scenario' => 'payment', 'schema' => 'nonprofit_payment', 'supports_lines' => true,
            'is_financial' => true, 'requires_acceptance' => false,
        ],
        'membership_invoice' => [
            'name' => 'Membership Invoice', 'title' => 'Membership Subscription Invoice', 'category' => 'financial',
            'prefix' => 'MEM-I', 'scenario' => 'donation_membership', 'schema' => 'nonprofit', 'supports_lines' => true,
            'is_financial' => true, 'requires_acceptance' => false,
        ],
        'membership_receipt' => [
            'name' => 'Membership Receipt', 'title' => 'Membership Subscription Receipt', 'category' => 'financial',
            'prefix' => 'MEM-R', 'scenario' => 'payment', 'schema' => 'nonprofit_payment', 'supports_lines' => true,
            'is_financial' => true, 'requires_acceptance' => false,
        ],
    ],

    'industry_profiles' => [
        'general_business' => [
            'standard_quotation', 'proforma_invoice', 'standard_invoice', 'payment_receipt',
            'credit_note', 'delivery_note', 'pos_receipt', 'sales_order', 'goods_return_note',
        ],
        'restaurant_food_service' => [
            'standard_quotation', 'proforma_invoice', 'standard_invoice', 'payment_receipt',
            'credit_note', 'delivery_note', 'pos_receipt', 'catering_quotation', 'catering_invoice',
            'event_quotation', 'event_reservation_contract', 'event_booking_invoice', 'event_payment_receipt',
        ],
        'hotel_lodge_guesthouse' => [
            'standard_quotation', 'proforma_invoice', 'standard_invoice', 'payment_receipt', 'credit_note',
            'room_booking_quotation', 'room_booking_invoice', 'booking_payment_receipt', 'guest_folio',
            'long_stay_agreement', 'event_quotation', 'event_reservation_contract',
            'event_booking_invoice', 'event_payment_receipt', 'catering_quotation', 'catering_invoice',
            'security_deposit_request', 'security_deposit_receipt', 'damage_assessment', 'damage_charge_invoice', 'security_deposit_settlement',
        ],
        'hotel_with_restaurant' => [
            'standard_quotation', 'proforma_invoice', 'standard_invoice', 'payment_receipt', 'credit_note', 'delivery_note', 'pos_receipt',
            'room_booking_quotation', 'room_booking_invoice', 'booking_payment_receipt', 'guest_folio',
            'long_stay_agreement', 'event_quotation', 'event_reservation_contract',
            'event_booking_invoice', 'event_payment_receipt', 'catering_quotation', 'catering_invoice',
            'security_deposit_request', 'security_deposit_receipt', 'damage_assessment', 'damage_charge_invoice', 'security_deposit_settlement',
        ],
        'property_management_rentals' => [
            'standard_quotation', 'proforma_invoice', 'standard_invoice', 'payment_receipt', 'credit_note',
            'rental_quotation', 'lease_agreement', 'rental_invoice', 'rent_receipt',
            'security_deposit_request', 'security_deposit_receipt', 'damage_assessment', 'damage_charge_invoice', 'security_deposit_settlement', 'owner_statement',
            'event_quotation', 'event_reservation_contract', 'event_booking_invoice', 'event_payment_receipt',
        ],
        'professional_services' => [
            'standard_quotation', 'proforma_invoice', 'standard_invoice', 'payment_receipt', 'credit_note',
            'service_proposal', 'service_contract', 'service_invoice', 'retainer_receipt',
        ],
        'retail_wholesale' => [
            'standard_quotation', 'proforma_invoice', 'standard_invoice', 'payment_receipt', 'credit_note',
            'pos_receipt', 'sales_order', 'delivery_note', 'goods_return_note',
        ],
        'construction_contracting' => [
            'standard_quotation', 'standard_invoice', 'payment_receipt', 'credit_note',
            'construction_estimate', 'construction_work_order', 'progress_invoice', 'completion_certificate',
        ],
        'healthcare_clinic' => [
            'standard_quotation', 'standard_invoice', 'payment_receipt', 'credit_note',
            'patient_estimate', 'patient_invoice', 'medical_payment_receipt', 'insurance_claim_summary',
        ],
        'education_training' => [
            'standard_quotation', 'standard_invoice', 'payment_receipt', 'credit_note',
            'tuition_invoice', 'fee_receipt', 'enrollment_confirmation',
        ],
        'automotive_services' => [
            'standard_quotation', 'standard_invoice', 'payment_receipt', 'credit_note',
            'vehicle_service_estimate', 'repair_work_order', 'vehicle_service_invoice',
        ],
        'logistics_transport' => [
            'standard_quotation', 'standard_invoice', 'payment_receipt', 'credit_note',
            'freight_quotation', 'consignment_note', 'freight_invoice', 'proof_of_delivery',
        ],
        'nonprofit_membership' => [
            'standard_quotation', 'standard_invoice', 'payment_receipt', 'credit_note',
            'donation_acknowledgement', 'donation_receipt', 'membership_invoice', 'membership_receipt',
        ],
    ],

    'default_scenario' => [
        'general_business' => 'sale',
        'restaurant_food_service' => 'sale',
        'hotel_lodge_guesthouse' => 'short_stay',
        'hotel_with_restaurant' => 'short_stay',
        'property_management_rentals' => 'rental',
        'professional_services' => 'professional_service',
        'retail_wholesale' => 'retail_order',
        'construction_contracting' => 'construction_project',
        'healthcare_clinic' => 'healthcare_service',
        'education_training' => 'education_fee',
        'automotive_services' => 'automotive_service',
        'logistics_transport' => 'logistics_shipment',
        'nonprofit_membership' => 'donation_membership',
    ],

    'schema_fields' => [
        'commercial' => [
            ['key' => 'customer_reference', 'label' => 'Customer reference', 'type' => 'text'],
            ['key' => 'purchase_order_reference', 'label' => 'Purchase order reference', 'type' => 'text'],
            ['key' => 'delivery_date', 'label' => 'Delivery or service date', 'type' => 'date'],
            ['key' => 'payment_terms', 'label' => 'Payment terms', 'type' => 'text'],
            ['key' => 'payment_method', 'label' => 'Payment method', 'type' => 'text'],
        ],
        'payment' => [
            ['key' => 'invoice_reference', 'label' => 'Invoice reference', 'type' => 'text'],
            ['key' => 'payment_date', 'label' => 'Payment date', 'type' => 'date', 'required' => true],
            ['key' => 'payment_method', 'label' => 'Payment method', 'type' => 'text', 'required' => true],
            ['key' => 'payment_reference', 'label' => 'Payment reference', 'type' => 'text'],
            ['key' => 'amount_in_words', 'label' => 'Amount in words', 'type' => 'text'],
        ],
        'rental_payment' => [
            ['key' => 'property_name', 'label' => 'Property', 'type' => 'text', 'required' => true],
            ['key' => 'unit_reference', 'label' => 'Unit or shop', 'type' => 'text'],
            ['key' => 'rental_period', 'label' => 'Rental period', 'type' => 'text'],
            ['key' => 'payment_date', 'label' => 'Payment date', 'type' => 'date', 'required' => true],
            ['key' => 'payment_method', 'label' => 'Payment method', 'type' => 'text', 'required' => true],
            ['key' => 'payment_reference', 'label' => 'Payment reference', 'type' => 'text'],
            ['key' => 'deposit_type', 'label' => 'Deposit classification', 'type' => 'select', 'options' => ['refundable' => 'Refundable', 'non_refundable' => 'Non-refundable', 'not_applicable' => 'Not applicable']],
        ],
        'stay_payment' => [
            ['key' => 'booking_reference', 'label' => 'Booking reference', 'type' => 'text'],
            ['key' => 'guest_name', 'label' => 'Guest name', 'type' => 'text'],
            ['key' => 'stay_period', 'label' => 'Stay period', 'type' => 'text'],
            ['key' => 'payment_date', 'label' => 'Payment date', 'type' => 'date', 'required' => true],
            ['key' => 'payment_method', 'label' => 'Payment method', 'type' => 'text', 'required' => true],
            ['key' => 'payment_reference', 'label' => 'Payment reference', 'type' => 'text'],
        ],
        'lease' => [
            ['key' => 'property_name', 'label' => 'Property', 'type' => 'text', 'required' => true],
            ['key' => 'unit_reference', 'label' => 'Unit, shop or room', 'type' => 'text'],
            ['key' => 'property_address', 'label' => 'Property address', 'type' => 'textarea', 'required' => true],
            ['key' => 'permitted_use', 'label' => 'Permitted use', 'type' => 'text'],
            ['key' => 'lease_start', 'label' => 'Start date', 'type' => 'date', 'required' => true],
            ['key' => 'lease_end', 'label' => 'End date', 'type' => 'date'],
            ['key' => 'payment_frequency', 'label' => 'Payment frequency', 'type' => 'select', 'options' => ['monthly' => 'Monthly', 'quarterly' => 'Quarterly', 'annually' => 'Annually', 'one_off' => 'One-off']],
            ['key' => 'rent_amount', 'label' => 'Rent per period', 'type' => 'number'],
            ['key' => 'contract_total', 'label' => 'Total contract value', 'type' => 'number'],
            ['key' => 'security_deposit', 'label' => 'Security Deposit (Refundable, held outside invoice income)', 'type' => 'number'],
            ['key' => 'utilities_responsibility', 'label' => 'Utilities responsibility', 'type' => 'textarea'],
            ['key' => 'maintenance_responsibility', 'label' => 'Maintenance responsibility', 'type' => 'textarea'],
            ['key' => 'termination_notice_days', 'label' => 'Termination notice (days)', 'type' => 'number'],
            ['key' => 'special_conditions', 'label' => 'Special conditions', 'type' => 'textarea'],
        ],
        'stay' => [
            ['key' => 'booking_reference', 'label' => 'Booking reference', 'type' => 'text'],
            ['key' => 'booking_date', 'label' => 'Booking date', 'type' => 'date', 'required' => true],
            ['key' => 'arrival_date', 'label' => 'Arrival date', 'type' => 'date', 'required' => true],
            ['key' => 'arrival_time', 'label' => 'Arrival time', 'type' => 'time', 'required' => true],
            ['key' => 'checkout_date', 'label' => 'Checkout date', 'type' => 'date', 'required' => true],
            ['key' => 'checkout_time', 'label' => 'Checkout time', 'type' => 'time', 'required' => true],
            ['key' => 'number_of_days', 'label' => 'Billable stay (nights)', 'type' => 'number'],
            ['key' => 'stay_duration', 'label' => 'Stay duration', 'type' => 'text'],
            ['key' => 'adults', 'label' => 'Adults', 'type' => 'number'],
            ['key' => 'children', 'label' => 'Children', 'type' => 'number'],
            ['key' => 'room_summary', 'label' => 'Rooms and accommodation', 'type' => 'textarea'],
            ['key' => 'rate_plan', 'label' => 'Rate plan', 'type' => 'text'],
            ['key' => 'extras', 'label' => 'Extras and guest services', 'type' => 'textarea'],
            ['key' => 'payment_deposit_amount', 'label' => 'Payment Deposit (Advance)', 'type' => 'number'],
            ['key' => 'balance_due_date', 'label' => 'Balance due date', 'type' => 'date'],
            ['key' => 'payment_method', 'label' => 'Payment method', 'type' => 'text'],
        ],
        'event_payment' => [
            ['key' => 'event_reference', 'label' => 'Event booking reference', 'type' => 'text'],
            ['key' => 'event_title', 'label' => 'Event title', 'type' => 'text'],
            ['key' => 'venue', 'label' => 'Venue', 'type' => 'text'],
            ['key' => 'event_date', 'label' => 'Event date', 'type' => 'date'],
            ['key' => 'payment_date', 'label' => 'Payment date', 'type' => 'date', 'required' => true],
            ['key' => 'payment_method', 'label' => 'Payment method', 'type' => 'text', 'required' => true],
            ['key' => 'payment_reference', 'label' => 'Payment reference', 'type' => 'text'],
        ],
        'event' => [
            ['key' => 'event_type', 'label' => 'Event type', 'type' => 'select', 'required' => true, 'options' => ['wedding' => 'Wedding', 'birthday' => 'Birthday', 'conference' => 'Conference', 'meeting' => 'Meeting', 'party' => 'Party', 'music_show' => 'Music show', 'other' => 'Other']],
            ['key' => 'event_title', 'label' => 'Event title or theme', 'type' => 'text'],
            ['key' => 'event_date', 'label' => 'Event date', 'type' => 'date', 'required' => true],
            ['key' => 'start_time', 'label' => 'Start time', 'type' => 'time'],
            ['key' => 'end_time', 'label' => 'End time', 'type' => 'time'],
            ['key' => 'expected_guests', 'label' => 'Expected guests', 'type' => 'number'],
            ['key' => 'venue', 'label' => 'Venue', 'type' => 'text', 'required' => true],
            ['key' => 'seating_style', 'label' => 'Seating style', 'type' => 'select', 'options' => ['banquet' => 'Banquet', 'theatre' => 'Theatre', 'cocktail' => 'Cocktail', 'classroom' => 'Classroom', 'custom' => 'Custom']],
            ['key' => 'decor_requirements', 'label' => 'Decor requirements', 'type' => 'textarea'],
            ['key' => 'technical_requirements', 'label' => 'Technical requirements', 'type' => 'textarea'],
            ['key' => 'menu_package', 'label' => 'Menu or catering package', 'type' => 'textarea'],
            ['key' => 'service_style', 'label' => 'Service style', 'type' => 'select', 'options' => ['buffet' => 'Buffet', 'plated' => 'Plated', 'cocktail' => 'Cocktail', 'not_applicable' => 'Not applicable']],
            ['key' => 'beverage_options', 'label' => 'Beverage options', 'type' => 'text'],
            ['key' => 'dietary_requirements', 'label' => 'Dietary requirements', 'type' => 'text'],
            ['key' => 'allergies', 'label' => 'Allergies', 'type' => 'text'],
            ['key' => 'add_ons', 'label' => 'Add-ons and optional services', 'type' => 'textarea'],
            ['key' => 'equipment_rental', 'label' => 'Equipment rental', 'type' => 'textarea'],
            ['key' => 'corkage_option', 'label' => 'Corkage or kitchen access', 'type' => 'textarea'],
            ['key' => 'early_access', 'label' => 'Early access arrangement', 'type' => 'textarea'],
            ['key' => 'reservation_fee', 'label' => 'Reservation fee', 'type' => 'number'],
            ['key' => 'security_deposit', 'label' => 'Security Deposit (Refundable, not invoice income)', 'type' => 'number'],
            ['key' => 'payment_deposit_amount', 'label' => 'Payment Deposit (Advance toward event price)', 'type' => 'number'],
            ['key' => 'balance_due_date', 'label' => 'Balance due date', 'type' => 'date'],
            ['key' => 'payment_method', 'label' => 'Payment method', 'type' => 'text'],
            ['key' => 'additional_notes', 'label' => 'Additional notes', 'type' => 'textarea'],
        ],
        'damage_assessment' => [
            ['key' => 'inspection_date', 'label' => 'Inspection date', 'type' => 'date', 'required' => true],
            ['key' => 'asset_reference', 'label' => 'Property / unit / venue reference', 'type' => 'text', 'required' => true],
            ['key' => 'damage_description', 'label' => 'Damage or loss details', 'type' => 'textarea', 'required' => true],
            ['key' => 'evidence_reference', 'label' => 'Evidence / photo / report reference', 'type' => 'text'],
            ['key' => 'assessment_basis', 'label' => 'Repair or replacement assessment basis', 'type' => 'textarea', 'required' => true],
            ['key' => 'deposit_deduction', 'label' => 'Deduction from refundable security deposit', 'type' => 'number'],
            ['key' => 'excess_charge', 'label' => 'Damage amount above security deposit', 'type' => 'number'],
            ['key' => 'dispute_notes', 'label' => 'Client response or dispute notes', 'type' => 'textarea'],
        ],
        'deposit_settlement' => [
            ['key' => 'asset_reference', 'label' => 'Property / unit / room / venue reference', 'type' => 'text', 'required' => true],
            ['key' => 'amount_received', 'label' => 'Security deposit received', 'type' => 'number', 'required' => true],
            ['key' => 'damage_deductions', 'label' => 'Approved damage deductions', 'type' => 'number'],
            ['key' => 'amount_refunded', 'label' => 'Amount refunded', 'type' => 'number'],
            ['key' => 'refund_method', 'label' => 'Refund method', 'type' => 'text'],
            ['key' => 'refund_reference', 'label' => 'Refund reference', 'type' => 'text'],
            ['key' => 'settlement_date', 'label' => 'Settlement date', 'type' => 'date', 'required' => true],
        ],
        'professional' => [
            ['key' => 'project_reference', 'label' => 'Project or engagement reference', 'type' => 'text'],
            ['key' => 'scope', 'label' => 'Scope of services', 'type' => 'textarea', 'required' => true],
            ['key' => 'deliverables', 'label' => 'Deliverables', 'type' => 'textarea'],
            ['key' => 'service_start', 'label' => 'Service start date', 'type' => 'date'],
            ['key' => 'service_end', 'label' => 'Service end date', 'type' => 'date'],
            ['key' => 'billing_basis', 'label' => 'Billing basis', 'type' => 'select', 'options' => ['fixed_fee' => 'Fixed fee', 'time_and_materials' => 'Time and materials', 'milestone' => 'Milestone', 'retainer' => 'Retainer']],
            ['key' => 'milestones', 'label' => 'Milestones', 'type' => 'textarea'],
            ['key' => 'retainer_amount', 'label' => 'Retainer amount', 'type' => 'number'],
            ['key' => 'payment_terms', 'label' => 'Payment terms', 'type' => 'textarea'],
            ['key' => 'client_responsibilities', 'label' => 'Client responsibilities', 'type' => 'textarea'],
        ],
        'professional_payment' => [
            ['key' => 'project_reference', 'label' => 'Project or engagement reference', 'type' => 'text'],
            ['key' => 'invoice_reference', 'label' => 'Invoice reference', 'type' => 'text'],
            ['key' => 'payment_date', 'label' => 'Payment date', 'type' => 'date', 'required' => true],
            ['key' => 'payment_method', 'label' => 'Payment method', 'type' => 'text', 'required' => true],
            ['key' => 'payment_reference', 'label' => 'Payment reference', 'type' => 'text'],
        ],
        'construction' => [
            ['key' => 'project_reference', 'label' => 'Project reference', 'type' => 'text', 'required' => true],
            ['key' => 'site_address', 'label' => 'Site address', 'type' => 'textarea', 'required' => true],
            ['key' => 'scope', 'label' => 'Scope of works', 'type' => 'textarea', 'required' => true],
            ['key' => 'contract_value', 'label' => 'Contract value', 'type' => 'number'],
            ['key' => 'work_start', 'label' => 'Work start date', 'type' => 'date'],
            ['key' => 'work_end', 'label' => 'Expected completion date', 'type' => 'date'],
            ['key' => 'completion_percentage', 'label' => 'Completion percentage', 'type' => 'number'],
            ['key' => 'retention_percentage', 'label' => 'Retention percentage', 'type' => 'number'],
            ['key' => 'architect_reference', 'label' => 'Architect or engineer reference', 'type' => 'text'],
        ],
        'healthcare_billing' => [
            ['key' => 'patient_reference', 'label' => 'Patient reference', 'type' => 'text', 'required' => true],
            ['key' => 'service_date', 'label' => 'Service date', 'type' => 'date', 'required' => true],
            ['key' => 'provider_name', 'label' => 'Service provider', 'type' => 'text'],
            ['key' => 'insurer_name', 'label' => 'Insurer', 'type' => 'text'],
            ['key' => 'policy_reference', 'label' => 'Policy or member reference', 'type' => 'text'],
            ['key' => 'claim_reference', 'label' => 'Claim reference', 'type' => 'text'],
            ['key' => 'authorization_reference', 'label' => 'Pre-authorization reference', 'type' => 'text'],
        ],
        'healthcare_payment' => [
            ['key' => 'patient_reference', 'label' => 'Patient reference', 'type' => 'text', 'required' => true],
            ['key' => 'invoice_reference', 'label' => 'Invoice reference', 'type' => 'text'],
            ['key' => 'payment_date', 'label' => 'Payment date', 'type' => 'date', 'required' => true],
            ['key' => 'payment_method', 'label' => 'Payment method', 'type' => 'text', 'required' => true],
            ['key' => 'payment_reference', 'label' => 'Payment reference', 'type' => 'text'],
        ],
        'education_billing' => [
            ['key' => 'student_reference', 'label' => 'Student reference', 'type' => 'text', 'required' => true],
            ['key' => 'student_name', 'label' => 'Student name', 'type' => 'text', 'required' => true],
            ['key' => 'programme', 'label' => 'Programme or class', 'type' => 'text'],
            ['key' => 'academic_period', 'label' => 'Academic year or term', 'type' => 'text', 'required' => true],
            ['key' => 'enrollment_date', 'label' => 'Enrollment date', 'type' => 'date'],
            ['key' => 'guardian_name', 'label' => 'Parent or guardian', 'type' => 'text'],
        ],
        'education_payment' => [
            ['key' => 'student_reference', 'label' => 'Student reference', 'type' => 'text', 'required' => true],
            ['key' => 'academic_period', 'label' => 'Academic year or term', 'type' => 'text'],
            ['key' => 'invoice_reference', 'label' => 'Invoice reference', 'type' => 'text'],
            ['key' => 'payment_date', 'label' => 'Payment date', 'type' => 'date', 'required' => true],
            ['key' => 'payment_method', 'label' => 'Payment method', 'type' => 'text', 'required' => true],
            ['key' => 'payment_reference', 'label' => 'Payment reference', 'type' => 'text'],
        ],
        'automotive' => [
            ['key' => 'vehicle_registration', 'label' => 'Vehicle registration', 'type' => 'text', 'required' => true],
            ['key' => 'vin', 'label' => 'VIN / chassis number', 'type' => 'text'],
            ['key' => 'make_model', 'label' => 'Make and model', 'type' => 'text'],
            ['key' => 'odometer', 'label' => 'Odometer reading', 'type' => 'number'],
            ['key' => 'reported_fault', 'label' => 'Reported fault or request', 'type' => 'textarea'],
            ['key' => 'inspection_findings', 'label' => 'Inspection findings', 'type' => 'textarea'],
            ['key' => 'promised_date', 'label' => 'Promised completion date', 'type' => 'date'],
        ],
        'logistics' => [
            ['key' => 'shipment_reference', 'label' => 'Shipment reference', 'type' => 'text', 'required' => true],
            ['key' => 'shipper', 'label' => 'Shipper', 'type' => 'text', 'required' => true],
            ['key' => 'consignee', 'label' => 'Consignee', 'type' => 'text', 'required' => true],
            ['key' => 'origin', 'label' => 'Origin', 'type' => 'text', 'required' => true],
            ['key' => 'destination', 'label' => 'Destination', 'type' => 'text', 'required' => true],
            ['key' => 'dispatch_date', 'label' => 'Dispatch date', 'type' => 'date'],
            ['key' => 'delivery_date', 'label' => 'Delivery date', 'type' => 'date'],
            ['key' => 'carrier_vehicle', 'label' => 'Carrier or vehicle', 'type' => 'text'],
            ['key' => 'package_summary', 'label' => 'Packages, weight and dimensions', 'type' => 'textarea'],
            ['key' => 'tracking_reference', 'label' => 'Tracking reference', 'type' => 'text'],
        ],
        'nonprofit' => [
            ['key' => 'supporter_reference', 'label' => 'Donor or member reference', 'type' => 'text'],
            ['key' => 'campaign', 'label' => 'Campaign, fund or programme', 'type' => 'text'],
            ['key' => 'membership_period', 'label' => 'Membership period', 'type' => 'text'],
            ['key' => 'restriction', 'label' => 'Donation restriction or purpose', 'type' => 'textarea'],
            ['key' => 'tax_deductibility_note', 'label' => 'Approved tax deductibility note', 'type' => 'textarea'],
        ],
        'nonprofit_payment' => [
            ['key' => 'supporter_reference', 'label' => 'Donor or member reference', 'type' => 'text'],
            ['key' => 'campaign', 'label' => 'Campaign, fund or programme', 'type' => 'text'],
            ['key' => 'payment_date', 'label' => 'Payment date', 'type' => 'date', 'required' => true],
            ['key' => 'payment_method', 'label' => 'Payment method', 'type' => 'text', 'required' => true],
            ['key' => 'payment_reference', 'label' => 'Payment reference', 'type' => 'text'],
        ],
    ],
];
