@extends('layouts.app')
@section('title', __('hms::lang.guest_profiles'))
@section('content')
@include('hms::layouts.nav')
<section class="content-header"><h1>@lang('hms::lang.guest_profiles') <small>@lang('hms::lang.guest_profiles_help')</small></h1></section>
<section class="content"><div class="box box-default"><div class="box-body">{!! Form::open(['route'=>'hms.guests.index','method'=>'get','class'=>'form-inline']) !!}{!! Form::text('search',request('search'),['class'=>'form-control','placeholder'=>__('hms::lang.search_guest')]) !!}<button class="btn btn-primary">@lang('hms::lang.search')</button>{!! Form::close() !!}</div></div>
@forelse($profiles as $profile)<div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">{{ optional($profile->contact)->name ?: __('hms::lang.anonymized_guest') }} <small>{{ optional($profile->contact)->email }} {{ optional($profile->contact)->mobile }}</small></h3><div class="box-tools"><a href="{{ route('hms.guests.export',$profile->id) }}" class="btn btn-xs btn-default"><i class="fa fa-download"></i> @lang('hms::lang.export_data')</a></div></div><div class="box-body">
{!! Form::open(['route'=>['hms.guests.update',$profile->id],'method'=>'put']) !!}<div class="row"><div class="col-md-2"><div class="form-group">{!! Form::label('preferred_language',__('hms::lang.preferred_language')) !!}{!! Form::text('preferred_language',$profile->preferred_language,['class'=>'form-control','maxlength'=>12]) !!}</div></div><div class="col-md-2"><div class="form-group">{!! Form::label('nationality',__('hms::lang.nationality')) !!}{!! Form::text('nationality',$profile->nationality,['class'=>'form-control']) !!}</div></div><div class="col-md-2"><div class="form-group">{!! Form::label('date_of_birth',__('hms::lang.date_of_birth')) !!}{!! Form::date('date_of_birth',optional($profile->date_of_birth)->toDateString(),['class'=>'form-control']) !!}</div></div><div class="col-md-2"><div class="form-group">{!! Form::label('vip_level',__('hms::lang.vip_level')) !!}{!! Form::select('vip_level',['standard'=>'Standard','silver'=>'Silver','gold'=>'Gold','platinum'=>'Platinum'],$profile->vip_level,['class'=>'form-control','placeholder'=>__('lang_v1.none')]) !!}</div></div><div class="col-md-2"><div class="form-group">{!! Form::label('retention_until',__('hms::lang.retention_until')) !!}{!! Form::date('retention_until',optional($profile->retention_until)->toDateString(),['class'=>'form-control']) !!}</div></div><div class="col-md-2"><div class="checkbox" style="margin-top:25px"><label>{!! Form::checkbox('marketing_consent',1,$profile->marketing_consent) !!} @lang('hms::lang.marketing_consent')</label><br><label>{!! Form::checkbox('do_not_contact',1,$profile->do_not_contact) !!} @lang('hms::lang.do_not_contact')</label></div></div><div class="col-md-12"><div class="form-group">{!! Form::label('accessibility_needs',__('hms::lang.accessibility_needs')) !!}{!! Form::textarea('accessibility_needs',$profile->accessibility_needs,['class'=>'form-control','rows'=>2]) !!}</div></div></div><button class="btn btn-primary btn-sm">@lang('messages.update')</button>{!! Form::close() !!}
@if(!$profile->anonymized_at && (auth()->user()->can('superadmin') || auth()->user()->can('hms.anonymize_guests'))){!! Form::open(['route'=>['hms.guests.anonymize',$profile->id],'method'=>'post','style'=>'display:inline']) !!}<button class="btn btn-danger btn-sm pull-right" onclick="return confirm('{{ __('hms::lang.confirm_anonymize_guest') }}')">@lang('hms::lang.anonymize_profile')</button>{!! Form::close() !!}@elseif($profile->anonymized_at)<span class="label bg-gray pull-right">@lang('hms::lang.anonymized')</span>@endif
</div></div>@empty<div class="callout callout-info">@lang('hms::lang.no_guest_profiles')</div>@endforelse<div class="pull-right">{{ $profiles->appends(request()->query())->links() }}</div>
</section>@endsection
