@php
    $business = $document->business_snapshot ?: [];
    $party = $document->party_snapshot ?: [];
    $currencyCode = data_get($document->template_snapshot, 'currency_code', optional($document->currency)->code ?: '');
@endphp
<!doctype html>
<html><head><meta charset="utf-8"><style>
    @page { margin: 4mm; }
    body { font-family: sans-serif; color:#111827; font-size:8pt; line-height:1.35; }
    h1,p { margin:0 0 4px; } h1 { font-size:13pt; }
    .center { text-align:center; } .right { text-align:right; } .muted { color:#64748b; }
    .rule { border-top:1px dashed #475569; margin:7px 0; }
    table { width:100%; border-collapse:collapse; } th,td { padding:3px 1px; vertical-align:top; }
    .items th { border-bottom:1px solid #334155; } .items td { border-bottom:1px dotted #cbd5e1; }
    .total td { padding-top:5px; font-size:10pt; font-weight:bold; border-top:1px solid #111827; }
    .wrap { overflow-wrap:anywhere; }
</style></head><body>
<div class="center">
    <h1>{{ data_get($business, 'name') }}</h1>
    <div class="wrap">{{ data_get($business, 'address') }}</div>
    <div>{{ data_get($business, 'mobile') }}</div>
    @if(data_get($business, 'tax_number_1'))<div>{{ data_get($business, 'tax_label_1', 'Tax number') }}: {{ data_get($business, 'tax_number_1') }}</div>@endif
</div>
<div class="rule"></div>
<table><tr><td><strong>{{ $document->title }}</strong></td><td class="right">{{ $document->document_number }}</td></tr><tr><td>{{ optional($document->issue_date)->format('d M Y') }}</td><td class="right">{{ strtoupper($document->status) }}</td></tr></table>
@if(data_get($party, 'name') || data_get($party, 'business_name'))<p><strong>Customer:</strong> {{ data_get($party, 'business_name') ?: data_get($party, 'name') }}</p>@endif
<div class="rule"></div>
<table class="items"><thead><tr><th>Item</th><th class="right">Qty</th><th class="right">Amount</th></tr></thead><tbody>
@foreach($document->lines as $line)<tr><td>{{ $line->description }}</td><td class="right">{{ number_format($line->quantity, 2) }}</td><td class="right">{{ number_format($line->line_total, 2) }}</td></tr>@endforeach
</tbody></table>
<table><tr><td>Subtotal</td><td class="right">{{ $currencyCode }} {{ number_format($document->subtotal, 2) }}</td></tr>@if((float)$document->discount_amount !== 0.0)<tr><td>Discount</td><td class="right">{{ $currencyCode }} {{ number_format($document->discount_amount, 2) }}</td></tr>@endif @if((float)$document->tax_amount !== 0.0)<tr><td>Tax</td><td class="right">{{ $currencyCode }} {{ number_format($document->tax_amount, 2) }}</td></tr>@endif<tr class="total"><td>Total</td><td class="right">{{ $currencyCode }} {{ number_format($document->total_amount, 2) }}</td></tr>@if((float)$document->amount_paid !== 0.0)<tr><td>Paid</td><td class="right">{{ $currencyCode }} {{ number_format($document->amount_paid, 2) }}</td></tr><tr><td>Balance</td><td class="right">{{ $currencyCode }} {{ number_format($document->balance_due, 2) }}</td></tr>@endif</table>
@if($document->notes)<div class="rule"></div><p class="wrap">{{ $document->notes }}</p>@endif
<div class="rule"></div>
<p class="center muted">Thank you. Generated by CashERP.<br>{{ $document->document_number }}</p>
</body></html>
