@extends('layouts.app')
@section('title', __('hms::lang.guest_messaging'))
@section('content')
@include('hms::layouts.nav')
<section class="content-header"><h1>@lang('hms::lang.guest_messaging') <small>@lang('hms::lang.guest_messaging_help')</small></h1></section>
<section class="content"><div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">@lang('hms::lang.add_message_rule')</h3></div><div class="box-body">{!! Form::open(['route'=>'hms.guest_messages.store']) !!}<div class="row"><div class="col-md-3"><div class="form-group">{!! Form::label('hms_property_id',__('hms::lang.property')) !!}{!! Form::select('hms_property_id',$properties,null,['class'=>'form-control select2','placeholder'=>__('hms::lang.all_properties')]) !!}</div></div><div class="col-md-3"><div class="form-group">{!! Form::label('name',__('hms::lang.name').':*') !!}{!! Form::text('name',null,['class'=>'form-control','required']) !!}</div></div><div class="col-md-3"><div class="form-group">{!! Form::label('event_type',__('hms::lang.event').':*') !!}{!! Form::select('event_type',['pre_arrival'=>__('hms::lang.pre_arrival'),'arrival_day'=>__('hms::lang.arrival_day'),'in_stay'=>__('hms::lang.in_stay'),'pre_departure'=>__('hms::lang.pre_departure'),'post_departure'=>__('hms::lang.post_departure')],null,['class'=>'form-control']) !!}</div></div><div class="col-md-3"><div class="form-group">{!! Form::label('timing_offset_minutes',__('hms::lang.offset_minutes').':*') !!}{!! Form::number('timing_offset_minutes',0,['class'=>'form-control','required']) !!}</div></div><div class="col-md-12"><div class="form-group">{!! Form::label('subject',__('hms::lang.subject').':*') !!}{!! Form::text('subject',null,['class'=>'form-control','required']) !!}</div></div><div class="col-md-12"><div class="form-group">{!! Form::label('body',__('hms::lang.message').':*') !!}{!! Form::textarea('body',null,['class'=>'form-control','rows'=>4,'required']) !!}<p class="help-block">@lang('hms::lang.message_tags_help')</p></div></div><div class="col-md-12">{!! Form::hidden('channel','email') !!}<label>{!! Form::checkbox('requires_marketing_consent',1,false) !!} @lang('hms::lang.requires_marketing_consent')</label></div></div><button class="btn btn-primary">@lang('messages.save')</button>{!! Form::close() !!}</div></div>
<div class="box box-default"><div class="box-body table-responsive"><table class="table table-bordered"><thead><tr><th>@lang('hms::lang.name')</th><th>@lang('hms::lang.event')</th><th>@lang('hms::lang.property')</th><th>@lang('hms::lang.offset_minutes')</th><th>@lang('hms::lang.consent')</th><th>@lang('hms::lang.status')</th><th>@lang('messages.action')</th></tr></thead><tbody>@forelse($rules as $rule)<tr><td>{{ $rule->name }}</td><td>{{ ucwords(str_replace('_',' ',$rule->event_type)) }}</td><td>{{ $rule->hms_property_id ?: __('hms::lang.all_properties') }}</td><td>{{ $rule->timing_offset_minutes }}</td><td>{{ $rule->requires_marketing_consent ? __('messages.yes'):__('messages.no') }}</td><td>{{ $rule->is_active ? __('hms::lang.active'):__('hms::lang.inactive') }}</td><td>{!! Form::open(['route'=>['hms.guest_messages.toggle',$rule->id],'method'=>'post']) !!}<button class="btn btn-xs btn-default">{{ $rule->is_active ? __('hms::lang.deactivate'):__('hms::lang.activate') }}</button>{!! Form::close() !!}</td></tr>@empty<tr><td colspan="7">@lang('hms::lang.no_message_rules')</td></tr>@endforelse</tbody></table></div></div>
<div class="box box-default"><div class="box-header with-border"><h3 class="box-title">@lang('hms::lang.message_delivery_log')</h3></div><div class="box-body table-responsive"><table class="table table-bordered table-striped"><thead><tr><th>@lang('hms::lang.message_rule')</th><th>@lang('hms::lang.booking_reference')</th><th>@lang('hms::lang.guest')</th><th>@lang('hms::lang.scheduled_for')</th><th>@lang('hms::lang.attempts')</th><th>@lang('hms::lang.status')</th><th>@lang('hms::lang.failure_reason')</th></tr></thead><tbody>@forelse($logs as $log)<tr><td>{{ optional($log->rule)->name }}</td><td>{{ optional($log->booking)->ref_no }}</td><td>{{ optional($log->contact)->name }}</td><td>{{ @format_datetime($log->scheduled_for) }}</td><td>{{ $log->attempts }}</td><td><span class="label {{ $log->status === 'sent' ? 'bg-green' : ($log->status === 'failed' ? 'bg-red' : 'bg-yellow') }}">{{ ucfirst($log->status) }}</span></td><td>{{ $log->failure_reason ? \Illuminate\Support\Str::limit($log->failure_reason, 160) : '-' }}</td></tr>@empty<tr><td colspan="7">@lang('hms::lang.no_message_deliveries')</td></tr>@endforelse</tbody></table></div></div></section>
@endsection
